### ISSUE TITLE
Embed Support

### ISSUE THREAD

**Issue by amark** [scrimba/community#10]
It would be great (and good marketing for Scrimba) to be able to embed a scrimba "video" into other sites. That way when people blog, etc., they could embed scrimba which readers would find as delightful but also let readers click-through to see/discover the rest of scrimba and its awesomeness.

I got a simple <iframe> working, but there is no visual indicator to a reader that they need to "click play" or anything (and the buttons seemed to display wrong?), plus it kept on scrolling which was caused the scrimba player to get clipped.

Great work, you all.

**Comment by amark** [comment]
@perborgen following up from our HackerNews discussion: https://news.ycombinator.com/item?id=13815431 .

As a personal example, because I write/produce/create free educational content, I would be less likely to pay for embed support (because I'm not making money off of it). As a result, if I couldn't embed scrimba without paying, I wouldn't be able to use scrimba in my free content. If I can embed (I assume you'll have your name/watermark/whatever on it), then it is "win+win+win" for the reader, for me, and for you (as readers wind up discovering more great content through scrimba).

Meanwhile, all those "proprietary" "pay for" classes, like Udemy and others, would naturally want to keep their videos private, and their user's locked into their own platform as much as possible (remove scrimba watermark, white label, etc.). How many of these platforms have already tried building custom tools similar to scrimba for themselves? If now competitors can pay to adopt your  system, which is superior, there is good incentive which is win-win for them and you.

Of course, I'm biased wanting embed support to be freemium, but I think there is good reason/marketing around it.

**Comment by samtstern** [comment]
+1 to this request.  I work on Developer Relations and Firebase and I'd like to experiment with an embedded scrimba in a docs page or blog post.  Basic embedding support would enable that, but would be really cool to get some analytics as well.

**Comment by perborgen** [comment]
Thanks for sharing your thoughts on this @amark and @samtstern. 

We'll be working on implementing this feature in the near future.

**Comment by amark** [comment]
Great to hear! Again, if there are parts that are open source that we could help/contribute too, let me know!

**Comment by perborgen** [comment]
Hey all!

We've opened up for very basic embedding, check this [JSBin](https://jsbin.com/fiqiwet/edit?html,output) for an example on how it's done. There are still some issues (you can't edit inside of embeds and no fullscreen), however it'll be fixed in the next update.

**Comment by davekiss** [comment]
@perborgen embeds are currently erroring out, see JSBin link for error details

**Comment by judofyr** [comment]
@davekiss Oops. I've fixed it now.

**Comment by judofyr** [comment]
We've also added a complete embed code under the "Edit cast"-button (gear):

<img width="1011" alt="screen shot 2017-04-29 at 20 30 34" src="https://cloud.githubusercontent.com/assets/499/25557857/ce06a474-2d1a-11e7-9881-7caac639631a.png">

**Comment by Magwit** [comment]
I tried embedding but noted that it is not supported at the moment. Edit metadata does not have any embed option and the Embed section in the docs is empty too. The feature seems to have been rolled back. The latest update is probably issue [#115 ](https://github.com/scrimba/community/issues/115)

![scrimba_edit_metadata](https://user-images.githubusercontent.com/22026184/36062170-fac3af92-0e66-11e8-8ccf-d83acf117847.JPG)

**Comment by drozumek** [comment]
I'm waiting for embed options as well. Today I've discovered Scrimba and I'm AMAZED. That's the thing I was looking for.

**Comment by Min11Benja** [comment]
Ward

**Comment by perborgen** [comment]
Hey guys, if you set the source of an iframe to the URL of the cast, the embedding should work.
