### ISSUE TITLE
Axios npm package doesn't work

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#100]
Get's the following error message:

Error: No such file: lib/core/../defaults

**Comment by somebee** [comment]
This is the offending line in axios: https://github.com/axios/axios/blob/26b06391f831ef98606ec0ed406d2be1742e9850/lib/core/Axios.js#L3

```javascript
var defaults = require('./../defaults');
var utils = require('./../utils');
```

Maybe our resolver do not support the strange `./../` syntax? `../` is more common.

**Comment by judofyr** [comment]
I've deployed a fix for this now.
