### ISSUE TITLE
Can't get the D3 and Britecharts packages to work 

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#104]
Trying to log them, but they are both *null*.

**Comment by judofyr** [comment]
This is working as expected: https://github.com/d3/d3/blob/master/README.md#installing

> D3 is written using [ES2015 modules](http://www.2ality.com/2014/09/es6-modules-final.html). Create a [custom bundle using Rollup](https://bl.ocks.org/mbostock/bb09af4c39c79cffcde4), Webpack, or your preferred bundler. To import D3 into an ES2015 application, either import specific symbols from specific D3 modules:
> 
> ```js
> import {scaleLinear} from "d3-scale";
> ```
> 
> Or import everything into a namespace (here, `d3`):
> 
> ```js
> import * as d3 from "d3";
> ```

**Comment by judofyr** [comment]
Same with Britecharts. This works fine:

```javascript
import * as britecharts from 'britecharts';
```
