### ISSUE TITLE
Bug with resolving relative paths

### ISSUE THREAD

**Issue by ilyar** [scrimba/community#105]
https://scrimba.com/c/cvdeEu8 

> Error: No such file: dist/./.bemrc.js

*actual:*  `dist/./.bemrc.js`
*expect:*  `./.bemrc.js`

**Comment by judofyr** [comment]
I have fixed it locally, but the example still fails due to missing support of scoped NPM packages (#107). I'll let you know when I've deployed the fix.

**Comment by judofyr** [comment]
Fixed now.

**Comment by judofyr** [comment]
Your cast seems to still fail due to `@bem/entity-name` depending on the (native) `util` module.

**Comment by ilyar** [comment]
@judofyr  How is the file `index.pack.js` build, webpack?   how can I setup an plugin (https://github.com/bem/webpack-bem-loader)?

**Comment by judofyr** [comment]
@ilyar it's not built with Webpack, but with a custom resolver. Everything is being done client-side which is why we can't use Webpack or Rollup. We don't currently have any plans for a plugin system.
