### ISSUE TITLE
Cursor is a little off in mobile

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#111]
See the image below. The cursor seems to be a little bit too much to the left. 

Check the image below from the following screencast:

https://scrimba.com/c/cdq9zSq

![bilde 07 10 2017 18 11 21](https://user-images.githubusercontent.com/2429547/31313064-c46d026a-ab8b-11e7-9842-c84f2bd3e15d.png)

**Comment by somebee** [comment]
Doesn't seem to happen on ios 11. Anyone else experiencing this?

**Comment by somebee** [comment]
Closing this since pointer has been refactored.
