### ISSUE TITLE
Make text in search box in editor colored

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#112]
The search feature in the editor (cmd + f) displays white text on white background. Here I've written 'react' in the search field, but you can't see it because the text and background is white.

<img width="1061" alt="skjermbilde 2017-10-07 kl 18 45 20" src="https://user-images.githubusercontent.com/2429547/31313183-cebc5bea-ab8f-11e7-8b8c-8102e91a8b3f.png">

**Comment by judofyr** [comment]
Doesn't seem to be a problem anymore?
