### ISSUE TITLE
Add embedding/sharing back in again

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#115]
There's a couple of users awaiting embedding, so we should find a nice way of introducing it again. It could be a part of a more general share panel.

**Comment by Magwit** [comment]
I tried embedding but noted that is in fact not supported at the moment. The Embed section in the docs is empty too. The feature seems to have been rolled back. The latest update that I found was issue [#115](https://github.com/scrimba/community/issues/115) 

![scrimba_edit_metadata](https://user-images.githubusercontent.com/22026184/36062149-9e5f0972-0e66-11e8-9c08-fb0f4c032633.JPG)
