### ISSUE TITLE
Improve UI/UX of settings dialog

### ISSUE THREAD

**Issue by MeoMix** [scrimba/community#13]
The settings dialog currently looks like this on first load: 
![image](https://cloud.githubusercontent.com/assets/1380995/23689331/b7f8153a-036e-11e7-8fb9-4b01cd9609a8.png)

A few things stand out as issues:

- The overall UI feels cramped & overly busy.

- The `<select>` is initially blank, but also offers a 'None' option in the dropdown.

- The 'Add' button gets darker when hovering. Usually things grow in visual priority, rather than lessen, when hovered.

- Dialog does not have usual methods of closing dialog (click outside of it, X in top corner).

- Bug: Positioned incorrectly in scrolled pages #22

Also...

- Consider tinting the background slightly when the dialog is open to detract background noise.

- Review design guidelines for dialogs: https://material.io/guidelines/components/dialogs.html

**Comment by judofyr** [comment]
Oh yes, the settings dialog is not our proudest creation. We're going to create a proper, unified dialog/modal interface which we can use across Scrimba.
