### ISSUE TITLE
Cannot require firebase/firestore

### ISSUE THREAD

**Issue by somebee** [scrimba/community#132]
Fails on `require("firebase/firestore")` which is needed to use the new firestore api.

```
Error: Unknown require: grpc (in module /node_modules/@firebase/firestore/dist/cjs/src/platform_node/grpc_connection.js) 
(/node_modules/@firebase/firestore/dist/cjs/src/platform_node/grpc_connection.js:29)
```

**Comment by judofyr** [comment]
Very strange. The `@firebase/firestore` package only have `grpc` as a devDependency although it seems to be required outside of development: https://unpkg.com/@firebase/firestore@0.1.4/package.json

**Comment by judofyr** [comment]
Okay, there was a separate issue as well. We didn't correctly respect the `browser`-field in some cases. I've fixed it now and it will be available in the next deploy.

And it turns out having `grpc` as devDependency is great because the browser-version doesn't seem to depend on it.
