### ISSUE TITLE
User can't clone casts

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#133]
@Pistus reported that he can't clone casts. He gets 'Please select template'. Has tried on two different casts. 

![screen shot 2017-11-07 at 08 59 16](https://user-images.githubusercontent.com/2429547/32485781-d701a472-c3a4-11e7-8042-6296afcfb073.png)

It does however work for me, which is a bit weird.

**Comment by Pistus** [comment]
Tried two casts in Chrome. Tried again with a different user in Firefox. Same issue for all attempts. 

When clicking confirm an event is triggered on the hidden 'parent_id' input element, so I assume this is the problem.

`<input class="parentId invisible" name="parent_id" required="" type="text">`

**Comment by somebee** [comment]
I'm having some trouble reproducing this, but working on it.

**Comment by kalicki** [comment]
Hey! Have a other input:hidden In the same form ... Both inputs (input.parentID) save the same values, make sense?
