### ISSUE TITLE
Re-record (trim) doesn't always work (but worked after refresh)

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#135]
Trying to re-record (trim) on this screencast doesn't result in a recording. I get the prompt which asks for a confirmation, and while I click 'Ok', it doesn't go into *recording mode*. It jumps back to the previous non-recording state.

https://scrimba.com/c/cM3matQ

However, it worked when I refreshed.

**Comment by Pistus** [comment]
Closing as stale issue.
