### ISSUE TITLE
Rename 'Build Project' and 'Save'

### ISSUE THREAD

**Issue by MeoMix** [scrimba/community#15]
I think 'Build Project' should be renamed to 'Save' and the keyboard shortcut for it updated to Ctrl+S (or similar). The current 'Save' button should be renamed to 'Fork'.

My gut reaction on first use was to hit Ctrl+S when I wanted to see my changes take effect. The rest of the suggested changes stem from this desire.

**Comment by perborgen** [comment]
This one has been renamed and shortcut added.
