### ISSUE TITLE
Double audio waves (only visually) appears in brushup mode

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#150]
Sometimes when editing a cast which has been re-recorded, it seems like both the audio waves appear in the brushup panel:

<img width="923" alt="skjermbilde 2017-11-14 kl 17 55 16" src="https://user-images.githubusercontent.com/2429547/33063151-ecb28360-cea1-11e7-8807-f526538fc3a2.png">

However, I'm still hearing the correct audio, so it seems to be a UI issue only.

**Comment by somebee** [comment]
I'm aware of it. Should be relatively easy to fix :)
