### ISSUE TITLE
image appears in root, but is actually in img folder

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#151]
When I try to drag the image into the img folder, apparently nothing happens. However, it has been moved, so when I try to access the image in the code, it exists in the img folder.

<img width="1076" alt="skjermbilde 2017-11-21 kl 13 03 11" src="https://user-images.githubusercontent.com/2429547/33071623-88a93ae2-cebc-11e7-8bce-6202a706d621.png">

**Comment by somebee** [comment]
Bug is related to deserializing snapshot, where the folder is created after the actual file. Should be relatively easy to fix

**Comment by somebee** [comment]
Fixed on staging
