### ISSUE TITLE
Browser preview keeps reloading endlessly

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#157]
Got a report from a user about the browser preview window reloading endlessly.

This has also happened to me before.

![bug](https://user-images.githubusercontent.com/2429547/33343647-68898878-d486-11e7-8834-2dd04bd6c8f2.png)

**Comment by somebee** [comment]
I think @judofyr should take a look at it. It might be related to some chrome extensions that our tracker doesn't like.
