### ISSUE TITLE
Project title resets after selecting template type

### ISSUE THREAD

**Issue by hoodwink73** [scrimba/community#162]
If we type in the name of the project before selecting the template, it resets to the name of the template when we select a template.

This results in a redundant effort from the user to name the project.

https://www.dropbox.com/s/sty3piypdhnfeat/Kapture%202017-12-01%20at%2012.31.48.gif?dl=0

**Comment by somebee** [comment]
Fixed now, will be deployed soon. Thanks for reporting :)
