### ISSUE TITLE
No sound (when replaying)

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#165]
Reported from this user on Medium:

https://medium.com/@webstractions/hey-per-i-have-been-reading-a-few-of-your-articles-about-css-grid-and-playing-around-with-it-on-825ea184e510

**Comment by ivarsu** [comment]
Can confirm. Am running latest stable build of Firefox(57.0.1).

**Comment by webstractions** [comment]
The screencast I viewed was https://scrimba.com/c/c2gd3T2 -- and as @ivarsu said, it works in Chrome.

**Comment by mmarcin8** [comment]
On the latest Firefox I am running on everything is fine

**Comment by webstractions** [comment]
I am using Firefox Developer 58.0b12 (64-bit).

**Comment by mmarcin8** [comment]
Firefox Quantum 58.0b12 (64-bit) beta version

**Comment by webstractions** [comment]
@mmarcin8 I just revisited that link, and the sound is working fine now! 

@perborgen You can close this issue. Not sure how it was fixed, or if it was even broken to begin with. Maybe it was something with Firefox version I was using at the time.
