### ISSUE TITLE
Scrimba player controls formatting bug Safari browser

### ISSUE THREAD

**Issue by gloc-mike** [scrimba/community#179]
I clicked on the following link re CSS Grid 101 (https://scrimba.com/p/pRB9Hw/c2gd3T2). It opens in Safari but the player controls at the top and bottom of the player are text only and not formatted correctly (see screenshots).

Top:
![screenshot 2017-12-18 13 30 04](https://user-images.githubusercontent.com/2324626/34104751-63eae068-e3fa-11e7-9922-a73a0854d0d1.png)

Bottom:
![screenshot 2017-12-18 13 30 14](https://user-images.githubusercontent.com/2324626/34104753-65f908e4-e3fa-11e7-92e4-f41b91317231.png)

Safari version:
![screenshot 2017-12-18 13 52 02](https://user-images.githubusercontent.com/2324626/34104819-a9b248de-e3fa-11e7-98e5-86136ea35ba5.png)

**Comment by somebee** [comment]
We started using ligatures for our icon font, and it doesn't seem like the font has loaded correctly for you. Are you on High Sierra? I cannot reproduce it on 11.0.0, nor Safari Technology Preview.

**Comment by gloc-mike** [comment]
No El Capitan:



Thanks
Michael

**Comment by somebee** [comment]
Turns out woff2 fonts are not supported on Safari El Capital. Will add fallback to woff and ttf.

**Comment by somebee** [comment]
Deployed a fix. Could you check if it works now? There might still be an issue where the text will flash before icons appear, since we're only inlining the woff2 font.

**Comment by gloc-mike** [comment]
Perfect! Don’t see the text at all, just icons!

Great, thanks!
