### ISSUE TITLE
Videos plays without audio

### ISSUE THREAD

**Issue by moreati** [scrimba/community#18]
When I first tried scrimba the visuals played but the audio did not. Retrying in an Incognito window (hence with all extensions disabled) allowed the audio to play.

Briefly experimenting, I believe the culprit was [Disable HTML5 Autoplay](https://chrome.google.com/webstore/detail/disable-html5-autoplay/efdhoaajjjgckpbkoglidkeendpkolai). FTR the other active extensions were uBlock Origin, Push Bullet, d3Coder, HTTPS Everywhere. Browser was Chromium 56.0.2924.76 on Ubuntu 16.10. It's probably unrelated, but the following was spamming the developer console at a high rate while the video was open

```
Blocked script execution in 'https://scrimba.com/cast/cast-6.preview' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
```

Please feel free to e.g. mark this WONTFIX, this is (probably) an extremely rare edge case and I am fine with that. I'm just documenting it here for completeness and any future fellow weirdos searching for the symptoms.

**Comment by metasean** [comment]
I'm running into a similar problem.  The first browser I tried is very locked down, but the second one not so much.

My open browser is Firefox Nightly 55.a01, with no security-related add-ons, although I do have "YouTube and more" to do video downloads.  

_Particularly telling_, is that if I pause the video, then use the bottom-right "Resume Video" button the audio starts in both browsers, but will be out of sync by however long the video was initially playing (e.g. if it took me 5 seconds to pause, then the audio will be 5 seconds behind the video).
