### ISSUE TITLE
Blocked script execution b/c 'allow-scripts' permission is not set.

### ISSUE THREAD

**Issue by 100ideas** [scrimba/community#20]
The console button isn't working for me on some of the casts (scrimbacasts? scrimbas?). I'm using macOS Chrome Version 56.0.2924.87 (64-bit). Not sure if this is because I have set an unusual Content Security Policy for chrome. Here's what I see in my browser's console when watching https://scrimba.com/cast/cast-327

```
Blocked script execution in 'https://scrimba.com/cast/cast-327.preview' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
```

docs on Content Security Policy headers here https://developer.chrome.com/extensions/contentSecurityPolicy

**Comment by judofyr** [comment]
This is most likely caused by extensions which automatically inject scripts into every frame on the page. Could you try to load the page in Incognito mode (without extensions) and see if they disappear?

**Comment by ph8tel** [comment]
I'm getting the same errors. Both in regular and incognito modes

**Comment by somebee** [comment]
Which casts is this happening on? The sandbox warning can happen when people include scripts in the html-part of the example, which is then rendered in the preview. So in that case it's really nothing to worry about, it's just that we don't preparse the html and remove the script-tags when we replay things in preview. The fact that you cannot open the console sounds like a bug though.

If you don't want to share the affected casts publicly you could PM me the link on gitter :)
