### ISSUE TITLE
Ability to download video for creator

### ISSUE THREAD

**Issue by donnyreza** [scrimba/community#200]
Would love to have this feature. Watermarking is fine as long as not ruins the video visual.

**Comment by perborgen** [comment]
This feature is not on our top priority list at the moment. However, if you as a creator want your screencast exported to a video, we'll do it manually for you without any cost, and send you the video, as specified in the FAQ:

https://github.com/scrimba/community/blob/master/FAQ.md#can-i-export-my-scrimba-screencast-to-a-normal-video

**Comment by tkssharma** [comment]
I would love to make  my learning Videos here... but how can i get those videos download !!

**Comment by buzzedison** [comment]
can i download my scrimba videos? would love to be able to do that. Just started using it and i think it is pretty cool.

**Comment by perborgen** [comment]
Unfortunately not @buzzedison .

**Comment by perborgen** [comment]
You can, however, download the audio file and then do a manual screen recording of the screencast. Then combine the two in a video editing tool.

**Comment by yassinose00** [comment]
> You can, however, download the audio file and then do a manual screen recording of the screencast. Then combine the two in a video editing tool.
Can't we see an online tool which does the work for us, like we see a youtube video downloader? it would be pretty helpful.

**Comment by rokublac** [comment]
A current work around I use to download screen casts is to use a browser extension tool such as this: [Screen Recorder](https://chrome.google.com/webstore/detail/screen-recorder/hniebljpgcogalllopnjokppmgbhaden?hl=en). This will allow you to record a cast along with the audio, and download it for offline viewing.

Just note that the extension suggested above exports your screen capture videos in **.webm** format. It is recommended to use [VLC Media Player](https://www.videolan.org/vlc/index.html) to view these files on your computer. Also download the VLC player app ([Android](https://play.google.com/store/apps/details?id=org.videolan.vlc&hl=en_AU) | [iOS](https://apps.apple.com/au/app/vlc-for-mobile/id650377962)) if you are going to view it on your mobile. 

For better accessibility with standard media players, I use an online [webm to mp4](https://video.online-convert.com/convert/webm-to-mp4) conversion tool to convert my files. So if you have trouble with viewing .webm format, try using an easy conversion tool such as the one noted above.

There are some other extensions out there that work pretty well but this is the one I've been using.

**Comment by perborgen** [comment]
I'm closing this one as @rokublac's solution is the currently recommended solution to get your casts downloaded as videos.

**Comment by Azim-me** [comment]
is it possible to download course from scrimba.com
