### ISSUE TITLE
BCryptJS doesn't work due to inexistence of native "Crypto" browser module.

### ISSUE THREAD

**Issue by PCabralSoftware** [scrimba/community#203]
**The problem:**
Trying to require the "bcryptjs" module outputs an error message.

**Steps to replicate this bug:**
1. Add the "bcryptjs" module inside a scrimba screencast.
2. Require the "bcryptjs" module (code below).
```js
var bcrypt = require('bcryptjs'); // Simple as that, when loading the modules, it outputs the error message (error object down below).
```

**Console error output example:**
```
Error: Cannot find module: crypto (from /node_modules/bcryptjs/dist/) ("https://...")
```

**Comment by perborgen** [comment]
Can you look at this one @judofyr ?

**Comment by judofyr** [comment]
This has been fixed in the latest development version.

<img width="698" alt="screen shot 2017-12-31 at 13 52 08" src="https://user-images.githubusercontent.com/499/34461700-d7d656f6-ee31-11e7-9d4c-c6964e26ed80.png">

Deploy coming soon.

**Comment by PCabralSoftware** [comment]
Thanks, @judofyr, I appreciate it!

**Comment by somebee** [comment]
Should be deployed now :)
