### ISSUE TITLE
Show length of Scrimba in thumbnail

### ISSUE THREAD

**Issue by rickysullivan** [scrimba/community#204]
Feature to show the length of each Scrimba.

**Comment by perborgen** [comment]
We do display is inside the screencasts, in the bottom right corner. Curious to know if you've seen this?

<img width="153" alt="screen shot 2017-12-31 at 13 00 23" src="https://user-images.githubusercontent.com/2429547/34461452-b9642970-ee2a-11e7-8409-9046d8264ea7.png">

Or did you mean displaying the length of them on the thumbnails on the front page?

**Comment by rickysullivan** [comment]
Search result thumbnails. Seeing an overview of a playlist showing each Scimba's length would be handy. Then I'd know how long it would take to watch a series of tutorials.

**Comment by perborgen** [comment]
Gotcha! Thanks for the quick reply.

**Comment by somebee** [comment]
Added in thumbnails now.
