### ISSUE TITLE
Fixing SEO for the home page

### ISSUE THREAD

**Issue by haraball** [scrimba/community#21]
When pasting the link to Scrimba in Slack, it looks like this:

<img width="194" alt="screen shot 2017-03-08 at 11 19 56" src="https://cloud.githubusercontent.com/assets/25930/23699965/8a44aa94-03f1-11e7-8a17-71beb0875b1c.png">

Same when googling Scrimba, the description isn't very good. 

<img width="595" alt="screen shot 2017-03-08 at 11 26 28" src="https://cloud.githubusercontent.com/assets/25930/23700106/209716c6-03f2-11e7-97f5-1b076f4e2b25.png">

Not a critical issue!

**Comment by perborgen** [comment]
We've added a meta description tag, so now it looks better. Closing this issue:

<img width="650" alt="skjermbilde 2017-03-25 kl 13 50 38" src="https://cloud.githubusercontent.com/assets/2429547/24322330/141ebffc-1162-11e7-8e8a-9f48a4b6756f.png">
