### ISSUE TITLE
Let visitors see/visit each other in a playground

### ISSUE THREAD

**Issue by aaronshaf** [scrimba/community#211]
I did an hour-long "learning party" at work today using Scrimba's playground feature. Everyone on the team wanted to be able to look at each other's playgrounds/forks. Only I, the host, was able to click around to see the forks/playgrounds of others.

**Comment by perborgen** [comment]
This is because we set the forks to "private" by default. Your students can, however, change the privacy of their forks by clicking the settings icon and making them "public". That should make them appear for everybody on your original playground.

Will that do the trick?
