### ISSUE TITLE
Download zip of project

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#216]
Ability to download a zip of project, which also contains package.json and a webpack file, so that the user can run the project locally.

Pending tasks:

- [x] Expose link in UI (add as menu-item in sidebar->files->cog)
- [x] Add directories correctly
- [x] Add package.json with NPM dependencies
- [x] Add webpack.config.js
- [x] Add assets
- [x] Supporting packing at a specific timestamp
- [x] Move into Files-area and make it timeline-dependent

**Comment by judofyr** [comment]
I couldn't figure out what the markup should be in the sidebar (with SidebarEntry, head, body and whatnot). Sending this along to @somebee for the final touches.
