### ISSUE TITLE
Settings modal position is off

### ISSUE THREAD

**Issue by lleaff** [scrimba/community#22]
On pages where you can scroll and open a video in a modal, the associated settings modal seems to be positioned relative to the initial 'unscrolled' viewport. On longer pages, this can cause the modal to be completely hidden to the user.

Tested on Chromium 56 on Ubuntu 16.04. No JS errors are spotted in console while the bug happens.

![screenshot_20170308_152313](https://cloud.githubusercontent.com/assets/9746807/23707648/74e69e42-0413-11e7-83a6-4692998f0b3d.png)

**Comment by judofyr** [comment]
Thanks for the report. I wasn't actually aware of that issue. We're going to overhaul the settings dialog in the near feature. I'm closing this issue so we can keep track related to the settings dialog in #13 instead.
