### ISSUE TITLE
There is no option for the output window to be detached

### ISSUE THREAD

**Issue by salmanulkhair** [scrimba/community#227]
it would be nice to have detached option for output window to move around it freely. Plus a unique URL could mean we can embed the output in our own pages perhaps.

**Comment by perborgen** [comment]
The mini-browser window? It is possible to move it around. You can grab it by the grey area at the top and drag&drop it.

**Comment by salmanulkhair** [comment]
Yes, the mini-browser window. its only draggable within boundaries of the app but not outside it. what I am suggesting is that it can be detached from the main app and could be open in a new tab in my chrome browser. Perhaps a unique URL will do that. plus there should be embed option so the other can embed it in his blog article with the specific timestamp like how people share and embed a youtube video. These are merely my suggestions.

**Comment by perborgen** [comment]
Thanks for the suggestion, but we're not going to implement this at the moment.
