### ISSUE TITLE
Interacting with Code & Video can be one step

### ISSUE THREAD

**Issue by deadcoder0904** [scrimba/community#232]
Not sure if this is possible, but it feels a lot boring to `Code` then Click `Resume Watching` & then Click `Play Button`. I think it should directly be possible to click `Play Button` to Play the Video after `Live Coding`. I think it would be better UX.

**Comment by perborgen** [comment]
Yeah, I really like this suggestion! We'll look into it.

**Comment by perborgen** [comment]
This one has been fixed, so closing this issue.
