### ISSUE TITLE
Videos speed cannot be reduced when made 2x.

### ISSUE THREAD

**Issue by vinchauhan** [scrimba/community#235]
It not working - and very annoying as you can't got back to 1x - even if you refresh. Or play any other course.

**Comment by vinchauhan** [comment]
Only doesnt work on Chrome but works on Firefox

**Comment by somebee** [comment]
Do you have any extensions that might interfer? Works on latest Chrome here.

**Comment by vinchauhan** [comment]
I am running - Version 63.0.3239.132 (Official Build) (64-bit).

Updating to see if it will fix.

**Comment by Freedom41** [comment]
I changed the video speed by reducing magnification (CTRL + ).......  which worked for me.

**Comment by somebee** [comment]
This is very strange .. does reducing magnification help for others as well?
We only store the playbackRate in sessionStorage, which should be unique per tab / tab-session. If it doesn't reset even after restarting the browser, I'm not really sure.

**Comment by somebee** [comment]
Finally fixed this. We didn't take browser-zoom into account when calculating mouse position on the slider. @Freedom41 thanks for the tip 👍
