### ISSUE TITLE
Broken D3 tutorial casts

### ISSUE THREAD

**Issue by omerbayram** [scrimba/community#244]
I can't play these two casts: (D3 tutorial part 1 and 2 by perborgen)

https://scrimba.com/p/pEKMsN/cast-1953
https://scrimba.com/p/pEKMsN/c3kE4Ta

I can here the sound, but there is no visual. I can open other screen-casts without problem. I tried css flexbox tutorials, and i can see all the videos in this series.

I tried to open D3 tutorial casts in Firefox 58.0.1 and Chrome 64.0.3282.140 on Windows 10. In both cases, i could hear the audio but no video or code.

Cheers

**Comment by perborgen** [comment]
Thanks for reporting this! Any ideas @somebee or @judofyr ?

**Comment by judofyr** [comment]
I've fixed this locally now. Will work in the next deploy.
