### ISSUE TITLE
Brushup options ('Cut', 'Silence' etc) are broken

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#246]
I highlight an area in the timeline, and then the menu with the options (Cut, Silence etc) pops up. However, nothing happens when clicking on the options.

**Comment by michaelerobertsjr** [comment]
@perborgen any updates on when this will have a resolution, or if there are any known work arounds?

**Comment by perborgen** [comment]
@michaelerobertsjr This one was recently fixed, we just forgot to update the issue. Sorry about that!
