### ISSUE TITLE
About page layout bug.

### ISSUE THREAD

**Issue by s0kil** [scrimba/community#247]
![screenshot_20180213-135554](https://user-images.githubusercontent.com/24403355/36168005-be46dc72-10c5-11e8-8eeb-e736ef55baa5.png)

**Comment by DanielSokil** [comment]
![img_20180213_135804](https://user-images.githubusercontent.com/24403355/36168105-f7ff6074-10c5-11e8-8077-0372f435b8a9.jpg)

**Comment by scanf** [comment]
This is reproducible on iOS when using in-app browsers

![Learn to Code with Interactive Tutorials  Scrimba.png](https://gitspeak.com/-/nUp3m6L44a23b/Learn%20to%20Code%20with%20Interactive%20Tutorials%20%20Scrimba.png)
