### ISSUE TITLE
Mobile: rendering issues

### ISSUE THREAD

**Issue by zaydek** [scrimba/community#267]
This can be grouped with https://github.com/scrimba/community/issues/265.

I've attached screenshots of the issue. There is at least one layout issue on the homepage and when I open one of the videos, nothing renders besides the background. This might be my fault because I'm using an iPhone 6 Plus using Safari on iOS 10.3.3. Just want to make sure the issue is known.

![img_5547](https://user-images.githubusercontent.com/6156990/37079617-8867462e-2226-11e8-9a14-06f4c2ca8eaf.PNG)
![img_5548](https://user-images.githubusercontent.com/6156990/37079618-88f20f70-2226-11e8-8007-32a3d6113239.PNG)

**Comment by scanf** [comment]
The front page has changed a lot since this was opened. Please create new issues for issues on mobile.

Thanks.
