### ISSUE TITLE
Brushup panel isn't closed when navigating away from the space

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#271]
If the Brush Up Panel is open when cloning a workspace the window of the previous workspace stays on top of the new workspace and I have no toggle to close it. A refresh takes care of it, but it’s still a bug. :grinning: See here:

https://drive.google.com/file/d/1OfOojgvgRiSQ2Vsrmxtld_-NVs_R66FM/view

**Comment by scanf** [comment]
The interface has changed a bit since this.
