### ISSUE TITLE
Fuzzy Find algorithm for Search bar

### ISSUE THREAD

**Issue by PCabralSoftware** [scrimba/community#273]
Scrimba search tab uses a simple string searching algorithm, a good idea for growing the reach for content producers and users that frequently try to search for a specific keyword, is to use a Fuzzy Find (Approximate String Matching) algorithm.

Here's the search bar with a query for "passport" (library PassportJS).
![Imgur](https://i.imgur.com/IComORT.png)
_"Could not find any results."_

Now, adding up two more characters.
![Imgur](https://i.imgur.com/YIVg8pl.png)
_"Found 1 result."_

Other types of algorithms, like Jaro-Winkler's and Levenshtein's distance, are also useful for the case.

Some useful links: [Approximate string matching](https://en.wikipedia.org/wiki/Approximate_string_matching), [Jaro-Winkler distance](https://en.wikipedia.org/wiki/Jaro%E2%80%93Winkler_distance), and [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance).

**Comment by judofyr** [comment]
We're probably going to focus on improving discoverability through categories/tags/"See more…" first, but fuzzy search would definitely help.

Note to self when I will implement this:

- Use [pg_trgm](https://www.postgresql.org/docs/current/static/pgtrgm.html) for finding similar words.
- Create a materialized view from `ts_stat(search_vector)` and create an gin_trgm_ops-index on that. (Alternative: Use an unstemmed tsvector instead).
- Pre-process the query and find possible misspellings

How to deal with alternative queries is always tricky. Should we show "Did you mean …"? Should the search results include the fuzzy matches as well? Maybe tuned by a threshold? I personally find Algolia's fuzzy matcher to be a bit too fuzzy. When searching for code related content "fuzziness" isn't always that interesting.

There are also some other language-specific tricks we can implement. Stripping "js" from the end of every word (in the stemmer) would probably improve search greatly.
