### ISSUE TITLE
Browser Refresh Minimizes the Browser

### ISSUE THREAD

**Issue by DanWahlin** [scrimba/community#275]
I'm used to clicking the "refresh" icon in the middle of the browser or clicking the icon next to the URL to refresh the browser. Doing either actions minimizes the browser now though. Not a huge problem since I can click the new "Reload Browser" button, but wanted to bring it up.

I also noticed that if I click on the minimized view of the browser I have to click twice for it to open to the full view. The workaround is to either click twice or click the "Reload Browser" button as mentioned above. 

Wanted to bring it up since it's a bit confusing initially if a user does click on the refresh icons but not on the "Refresh Browser" button.

**Comment by somebee** [comment]
This is definitely a bug. Will try to reproduce it here.

**Comment by scanf** [comment]
This bug has been resolved. Please reopen if you can reproduce.

Thanks.
