### ISSUE TITLE
Want to use Scrimba to create private recordings for internal team training

### ISSUE THREAD

**Issue by travis-eh** [scrimba/community#28]
**Feature request:**

Would be really cool if we could contribute to public lessons, but also have a space for private ones too. I see this being an incredibly useful tool for training my team. 

We want to do specific developer workflow tutorials that are unique to our environment, therefore not useful for the general public. 

An alternative would be an open-source version of Scrimba so we could implement it ourselves. However, I feel this would not support the broader Scrimba community as well as the initial feature request. 

Thoughts?

**Comment by perborgen** [comment]
Hey! 

We do plan to add support for that kind of usage in the future, where you'll have an organization where you can distribute private content amongst each other.

I'd be interested in scheduling a chat with you to hear which specific needs you'd have for this feature. Interested in that?

**Comment by travis-eh** [comment]
Yes, that would be great! I'll send an email to hello@scrimba.com shortly.
