### ISSUE TITLE
Question about JS calls from HTML

### ISSUE THREAD

**Issue by ghost** [scrimba/community#280]
I'm trying a test calling a js function and it runs fine if called from js script but a button click from html says it is not defined... so wondering is it me or something I am missing?

https://scrimba.com/c/cZ28pAb

Thanks,

JT

**Comment by somebee** [comment]
This should work, but currently we wrap the content of js-files in a function to be able to track certain things in the recorder. This means that functions defined in js will not be defined globally. We are looking into a way to support this. Until then, you can explicitly define them on window:

```javascript
window.doLoop = function() {
    let text = ""
    let i = 0
    do {
        text += "The number is " + i ;
        i++;
        console.log(i);
    }
    while (i < 10);
};

window.calc = function(btnVal) {
    console.log(btnVal);
};
```

**Comment by scanf** [comment]
The example works, so closing this.
