### ISSUE TITLE
A dedicated page for Enrolled Courses for an Account

### ISSUE THREAD

**Issue by paololatoja** [scrimba/community#284]
I would like the developers of Scrimba to add a feature wherein people can just go to their profile or a specific page to easily access all their enrolled courses and continue from the last time they left. No need to search for that particular tutorial in the website

**Comment by aphile** [comment]
I figured out how to find my enrolled courses on my Profile page, but I had to play a few seconds to get them to show up. (I wanted to enroll now and watch them later, and I thought they would show up immediately in my account when I clicked the Enroll button). Also, it would be really helpful to add the **title of the course** not just the title of the lesson to the page.

**Comment by perborgen** [comment]
Enrolled courses are now visible on your profile when you're logged in.
