### ISSUE TITLE
Support importing Vue.js single file components

### ISSUE THREAD

**Issue by padcom** [scrimba/community#291]
Any type of serious teaching of vue.js without using the single file components is pretty much useless.  You can explain simple concepts but explaining some more advanced elements is very hard to do without the SFCs.

Is there any way you can add support for importing and transpiling .vue files?

**Comment by rlmckenney** [comment]
I would be very interested in having Vue SFC support also.  Need to add vue-loader to the webpack config.

**Comment by Tod8Cruz** [comment]
I also need it!

**Comment by ArsalaBangash** [comment]
Was there any progress on this? 

Here's a link to some documentation: https://vue-loader.vuejs.org/guide

**Comment by perborgen** [comment]
This one is now supported.

**Comment by danielschmitz** [comment]
> This one is now supported.

but how? there are a template ?

**Comment by scanf** [comment]
@danielschmitz here is a screencast showing you how https://scrimba.com/c/cQqREQCN

I will create a new issue for updating the template.

Thanks.

**Comment by perborgen** [comment]
Vue SFC template  has been added
