### ISSUE TITLE
Adding libraries to a cast?

### ISSUE THREAD

**Issue by hlabas** [scrimba/community#3]
Would be super nice to be able to add some libraries to a given Javascript cast (like an SDK, an npm package or so), to demo some advanced use case.

**Comment by somebee** [comment]
We're working actively on this right now. The first approach (which we can deploy pretty soon) allows for adding script-sources directly. We're also experimenting with how to nicely include support for npm (and possibly webpack). Would being able to include scripts (like from https://unpkg.com/) be a good enough start?

**Comment by hlabas** [comment]
This would indeed!
Or some custom ones if npm is not available yet.

**Comment by perborgen** [comment]
You can now dd unpkg scripts, so I'm closing this issue.
