### ISSUE TITLE
Creation flow problems

### ISSUE THREAD

**Issue by kjetilholmefjord** [scrimba/community#30]
I tried to create my first Scrimba-cast yesterday. While successful, it could've been a lot smoother. Two comments:

**Naming cast**: I am not sure what the cast should be named before I have created it. My suggestion: remove this as a step before creating cast.

**Record button**: The record button is very small, and you're not really communicating (visually) that it's the most important button. My suggestion: make it a lot bigger, maybe let it take up half the screen. But inform me that it's a good idea to sometimes add some code before I start recording.

**Comment by somebee** [comment]
👍 We're working on improving the creation flow atm. Will definitely take these suggestions into account :)

**Comment by perborgen** [comment]
This has been fixed
