### ISSUE TITLE
Bad: Home Page, serious render issue... Chromium 64

### ISSUE THREAD

**Issue by kylebakerio** [scrimba/community#310]
![rendering error](https://user-images.githubusercontent.com/6391152/39669921-abd21938-50be-11e8-8505-9ad0007841e0.png)

**Comment by finetype** [comment]
Nothing in the console, fwiw.

No x-scrolling is possible, so that hidden content is invisible.

**Comment by bofeiw** [comment]
<img width="1238" alt="Screen Shot 2019-04-24 at 2 00 38 pm" src="https://user-images.githubusercontent.com/34177142/56631639-82ae4800-6699-11e9-892c-81ec2aae67df.png">
Yes it is a serious issue, which affects the user experience a lot. I could only click the little button to see more contents. Enabling x-scroll would be a basic feature.

**Comment by perborgen** [comment]
Fixed
