### ISSUE TITLE
Videos will not play in Chrome browser

### ISSUE THREAD

**Issue by cottonsean** [scrimba/community#311]
When trying to play videos in chrome browser, nothing happens.  The play button at bottom turns into a spinning loop, but video never plays.  I tested the issue on another computer running chrome and same issue.

**Comment by genchau** [comment]
@cottonsean Do you have a link to which video? I use Chrome with no issues.

**Comment by cottonsean** [comment]
https://scrimba.com/p/pV5eHk/c9EqQSD
I can't get Scrimba to work on any of the videos.  I have cleared my browsing history and cache, but no luck.

**Comment by carriere4** [comment]
worked fine for me 2 days ago - now having this issue

**Comment by Pistus** [comment]
Seems this is not a general issue so I´ll close this. Please reopen and add the browser version if it is still an issue.
