### ISSUE TITLE
Scrimba's site SSL is invalid

### ISSUE THREAD

**Issue by xtjoeywx** [scrimba/community#314]
The title says it all.

**Comment by Deseao** [comment]
I am experiencing this as well.
Chrome Version 66.0.3359.181 (Official Build) (64-bit) and Firefox 60.0.1 (64-bit).
I have been seeing this error intermittently, and am occasionally able to get to the homepage and https://scrimba.com/g/gintrotocss but never for more than a few seconds of browsing.
On my phone, the site works fine in the chrome browser.
<img width="1384" alt="screen shot 2018-05-24 at 10 29 39 am" src="https://user-images.githubusercontent.com/3657200/40495702-86a38812-5f3d-11e8-99db-1bb797ca1eda.png">
<img width="1306" alt="screen shot 2018-05-24 at 10 33 52 am" src="https://user-images.githubusercontent.com/3657200/40495868-fc1e2598-5f3d-11e8-915f-c8dc23136cb7.png">

**Comment by Deseao** [comment]
I would really love to be able to use this site for my interns but it still can't be loaded.

**Comment by xtjoeywx** [comment]
It's loading for me.. See image.



ᐧ
