### ISSUE TITLE
Audio lost

### ISSUE THREAD

**Issue by warent** [scrimba/community#32]
After recording a video, I recorded a second time for an additional couple seconds to clarify on some things. This apparently deleted the entire audio for the first ~4 mins of the video and only kept the last bit of audio. All visuals are intact

**Comment by vjandrei** [comment]
In the Intro to Reactjs there is no sound?

**Comment by perborgen** [comment]
Here: https://scrimba.com/casts/cast-206

**Comment by Maxim-Filimonov** [comment]
Same problem here https://scrimba.com/c/c6Vg4H3
We have tested the mic before recording and it was working fine.

**Comment by perborgen** [comment]
Did it only happen on that one @Maxim-Filimonov? Or is it a repeating problem?

**Comment by Maxim-Filimonov** [comment]
@perborgen  Same problem here from a different computer - https://scrimba.com/c/c6vEqf2

**Comment by scanf** [comment]
It's been over 900 days since this issue was created. Closing it for now. Please reopen if you can reproduce this.

Thanks.
