### ISSUE TITLE
*Feature request* Referral links

### ISSUE THREAD

**Issue by ZAYDEK** [scrimba/community#320]
I think it'd be super useful for Scrimba to feature referral links, so we have metrics about which links are getting the most traffic. E.g. scrimba.com/gbulma?ref=tw or scrimba.com/gbulma?ref=md-1 or  (unless this is a thing and I'm clueless).

**Comment by perborgen** [comment]
We can export where the traffic comes from for you, if that'll do the trick?

**Comment by zaydek** [comment]
Yes and no. I'm more interested in knowing which link in, for example, one Medium article was clicked the most. As in, the first? The image? The caption link, etc. It'd be nice to know so I can optimize articles for clickthrough rates. Just an idea.

**Comment by perborgen** [comment]
This is now possible
