### ISSUE TITLE
font-size setting to persist at least during a session

### ISSUE THREAD

**Issue by ptica** [scrimba/community#322]
Hi, nice work!

the font-size setting has a bit weird default state where the knob is on the top right of the span
so it seems the font-size is at the max but it could be increased after all once you drag it

and second thing: 
the font-size settings gets reset as soon as you advance to the next lesson in a series
where you have to increase it once again

**Comment by scanf** [comment]
Tried reproducing the second issye you mentioned and the font-size still gets reset when progressing to the next video.

**Comment by scanf** [comment]
I have fixed this and hopefully deployed soon, thanks.
