### ISSUE TITLE
CRITICAL: Workspace becomes useless if a file is made without extensions

### ISSUE THREAD

**Issue by iamtirado** [scrimba/community#326]
I accidentally forgot to write the extension on a new file, and it made my workspace entirely useless. All files on the sidebar become unresponsive to mouse clicks, and once I refresh the workspace, all the files become invisible and inaccessible. This has happened on two separate (LAB) workspaces. I have started twice, and would hate to have to start my project again. I will have lost a lot of work, if I cannot regain those files.

Workspace Before Refresh
<img width="1218" alt="screen shot 2018-06-28 at 11 48 15 am" src="https://user-images.githubusercontent.com/13579055/42045268-1e13d066-7ac9-11e8-9d67-431ece3d4080.png">

Workspace After Refreshing
<img width="1219" alt="screen shot 2018-06-28 at 11 48 25 am" src="https://user-images.githubusercontent.com/13579055/42045270-1f84de54-7ac9-11e8-9b3c-6343fc89a4e2.png">

**Comment by iamtirado** [comment]
@somebee

**Comment by somebee** [comment]
So sorry, I will look into it now.

**Comment by somebee** [comment]
Should be fixed now.
