### ISSUE TITLE
Using imba 1.3.x on Scrimba results in SyntaxError

### ISSUE THREAD

**Issue by Spaceghost** [scrimba/community#345]
```
SyntaxError: Unexpected token var
    at ModuleExecution.execute (cached-tracker-a0da3d7c248d38ea5415.js:1849)
    at ModuleLoader.preload (cached-tracker-a0da3d7c248d38ea5415.js:1878)
```

Switching to 1.2.x removes the problem for me and points me towards 1.3.x being problematic.

Here's a scrimbla to try: https://scrimba.com/c/cq9zgUm

**Comment by Spaceghost** [comment]
I'm going to close this, but my guess is CDN-related but it appears to work for now.

**Comment by evaisse** [comment]
Still have the problem

**Comment by somebee** [comment]
Sorry for this problem guys. Finally tracked down the issue and fixed it :)
