### ISSUE TITLE
Facebook share image isn't great

### ISSUE THREAD

**Issue by dhornbein** [scrimba/community#350]
Hi friends, I shared `https://scrimba.com/` on facebook and the image that pops up isn't very descriptive. Here's what it looks like on desktop:

![screen shot 2018-09-13 at 3 23 27 pm](https://user-images.githubusercontent.com/358427/45517151-76105b80-b76a-11e8-8abf-eeb6bc512827.png)

The `og:image` property isn't set so Facebook is grabbing one of the instructor photos.

[Facebook url linter page](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fscrimba.com%2F)

According to Facebooks [best practices guide](https://developers.facebook.com/docs/sharing/best-practices#images)

> Use images that are at least `1200 x 630` pixels for the best display on high resolution devices. At the minimum, you should use images that are `600 x 315` pixels to display link page posts with larger images. Images can be up to 8MB in size.

You just need to add a meta tag to your head, like this:

`<meta property="og:image" content="http://ia.media-imdb.com/images/rock.jpg" />`

**Comment by perborgen** [comment]
We've added a proper share image for Facebook now
