### ISSUE TITLE
Help with configuring unit tests on the platform

### ISSUE THREAD

**Issue by Maxim-Filimonov** [scrimba/community#351]
I've tried to configure mochajs to run on Scrimba. The same configuration runs fine locally. 
However, I'm having trouble marrying it with Scrimba JS preprocessor (cannot get to export any variables).
I've tried to use pack files but then mocha doesn't see the test files.
See [example](https://scrimba.com/c/c7KBdsa)

**Comment by perborgen** [comment]
Hey, it works if you use the following setup: https://scrimba.com/c/cLmWyHR
