### ISSUE TITLE
Code editing recording is not working? 

### ISSUE THREAD

**Issue by Maxim-Filimonov** [scrimba/community#353]
Code editing is not being recorded for some reason for this session. Tried in different browsers to view the same story.
https://scrimba.com/c/cGkaWf8

**Comment by davood1357** [comment]
https://secure.javhd.com

**Comment by perborgen** [comment]
Hi @Maxim-Filimonov, sorry about this, it's probably caused by some unfortunate connection error during this recording. It's not something which happens often is it?

**Comment by Maxim-Filimonov** [comment]
@perborgen the problem is overall stability. We are recording from two different laptops from different parts of the world and from 3 recordings only one was actually working. Other two had various problems(audio lost and this time the issue is instead with no action recorded).
