### ISSUE TITLE
Can't join Slack group

### ISSUE THREAD

**Issue by alexandre1985** [scrimba/community#357]
I would like to keep in touch with you on slack but I can't.
I have logged in into scrimba with a github login. In slack it asks for an email and password. I know my email but I have no password because of the github login.
How should I proceed?

**Comment by perborgen** [comment]
Hey, you don't need to use the same login, just choose an email and a password:

https://join.slack.com/t/scrimba/shared_invite/enQtNDE4MzY0NDY3NzkyLWFhMzg1YzQ4ZWIwOGMyYzhiZTYxMmEyZTAzMTE5ZTBmMzE4ZDA5ZjM1N2ZjMDZjMmE5M2M4ZDNkN2JjNGM2YzQ
