### ISSUE TITLE
Needs a list of features at the very least, if not a full set of docs

### ISSUE THREAD

**Issue by CreaturesInUnitards** [scrimba/community#36]
I was looking to see if there was a way to do a ```require()```, and found no docs whatsoever

**Comment by perborgen** [comment]
Adding basic documentation is on our list yes. To begin with it'll be a .md file in this repo.

**Comment by CreaturesInUnitards** [comment]
Yay! I see that you've added _DOCS.md_. I'll close this, and file specific issues against the shiny new file. Thanks!
