### ISSUE TITLE
Learning atom editor and CSS GRID

### ISSUE THREAD

**Issue by vinny1962** [scrimba/community#361]
I am new to CSS GRID and from what I have seen so far I really like it. I have created a index.html page and its ok. I have not done and programming in years. If it is possible can anyone point me to some videos were I can learn the CSS GRID programming in a order that is viable. I see allot of videos and I see none of them are in order for a programmer that's starting out. I have looked at many sites online for days and hours. I can not seem to find anything that's allowing me to learn in file order. 

Vinny

**Comment by Rob-Rychs** [comment]
Hi @vinny1962 now I'm not 100% on this (just a guess) but you might want to switch from learning atom editor to learning microsoft vscode text editor since future atom support looks uncertain

**Comment by perborgen** [comment]
Hey @vinny1962, here is my course on CSS Grid: https://scrimba.com/g/gR8PTE

You can start off with this article if you're a beginner and find the course too complex:https://medium.freecodecamp.org/learn-css-grid-in-5-minutes-f582e87b1228 

We don't have any tutorials on specific editors at Scrimba, as that doesn't suit our format.
