### ISSUE TITLE
allow right-click to open course in new tab

### ISSUE THREAD

**Issue by CloudZero458** [scrimba/community#364]
In Firefox, when you try to right-click a course to open it in a new tab, it opens the course in the current tab. Basically, right-click is interpreted as a left-click.

In Chrome, when you right-click, there is no option to open a course in a new tab.

**Comment by scanf** [comment]
This is also happens on the responsive design bootcamp playlist, https://scrimba.com/g/gresponsive

**Comment by scanf** [comment]
While nice to have, we probably don't want to encourage this.
