### ISSUE TITLE
React useEffect hook doesn't run on mount

### ISSUE THREAD

**Issue by cbejensen** [scrimba/community#367]
This is a weird one. It seems like the `useEffect` hook doesn't run when mounted, but only in Scrimba. I have the same code in codesandbox and it works as expected: https://codesandbox.io/s/v6333q207

You can see the background does not turn red once mounted in Scrimba, though: https://scrimba.com/c/czg2GCP

**Comment by perborgen** [comment]
Works when updating to the latest version of React :)
