### ISSUE TITLE
Renaming a file does not update code syntax highlighting

### ISSUE THREAD

**Issue by cedricium** [scrimba/community#368]
Related to #160.

**Steps to reproduce:**
1. create a file titled `test`
2. paste or type some code (such as `console.log('hello world')`)
3. expect the above to have no syntax highlighting due to missing file extension
4. rename file from `test` --> `test.js`
5. expect the file contents to be updated with JS syntax highlighting; actual result is missing syntax highlighting

**Comment by scanf** [comment]
The same thing applies to `.imba` files experienced this today where I had created a file with `.scrimba` suffix and then changing it to `.imba` did not update the syntax highlighter. Had to delete the file and use correct suffix.

**Comment by scanf** [comment]
I have looked into this and have a partial fix but need to test it some more and handle a couple of edge cases. Hopefully done before 2020 😊

**Comment by somebee** [comment]
To change the language of a monaco model you can use `monaco.editor.setModelLanguage(m,'language')`. We need to find a mapping from file extension to the correct language identifier.

**Comment by scanf** [comment]
The fix has been deployed, happy coding!
