### ISSUE TITLE
Full filesystem CRUD functionality

### ISSUE THREAD

**Issue by CreaturesInUnitards** [scrimba/community#37]
piggybacking on #33 

Should be able to add and delete folders as well as files. I want to use Scrimba for a full set of tutorials that use real-world architectures, so the lack of folders is a dealbreaker.

**Comment by CreaturesInUnitards** [comment]
I'll add that being able to delete/rename files, even in the absence of folders, would be a giant step forward.

**Comment by scanf** [comment]
@CreaturesInUnitards if you right click `FILES`, you should see context menu like the one below
<img width="192" alt="Screen Shot 2019-08-19 at 10 13 58" src="https://user-images.githubusercontent.com/925044/63249702-46b37a00-c26a-11e9-95b1-4f7e66368912.png">

**Comment by scanf** [comment]
I think this is now implemented, feel free to reopen if that's not the case.



Thanks.
