### ISSUE TITLE
Close browser when try import package.json

### ISSUE THREAD

**Issue by hernandoh** [scrimba/community#370]
I try import paackage.json into Scrimba web app from any two threre options and inmediatly the browser at close.

**Comment by ArsalaBangash** [comment]
Interesting. My browser doesn't close but my package.json won't be imported in any of my playgrounds. I have tried importing package.json files from large vue projects down to one generated by a quick npm init

**Comment by scanf** [comment]
Closing this for now, please repopen if you can reproduce.

Thanks.
