### ISSUE TITLE
something wrong while editing code

### ISSUE THREAD

**Issue by alexandre1985** [scrimba/community#373]
I'm on https://scrimba.com/p/pZ45Hz/cqVzJAq and if I try to edit the code just before the video ends, there will be a cursor input issue.
Im on Firefox in Linux.
Check it out for yourself

**Comment by scanf** [comment]
@alexandre1985 can you still reproduce this?

**Comment by alexandre1985** [comment]
I cannot reproduce.

The reason may be 2 things:
- It was a long time ago and my bug issue was not very descriptive
- I may be using at the time of the bug report, very strict browser configuration (that are located in [here](https://gist.github.com/alexandre1985/1ea2eedce7a7ce7ee9de1b413ee04cb6) ). So that may have caused some issues.

But, with those hardened configurations on Firefox I still have some issues. If someone has the time, can he/she point me out which configurations (of https://gist.github.com/alexandre1985/1ea2eedce7a7ce7ee9de1b413ee04cb6) should be modified, for full compatibility with scrimba.com on Firefox?

Thanks
