### ISSUE TITLE
Html tag hinders reading

### ISSUE THREAD

**Issue by q962** [scrimba/community#374]
Unable to close search tool
 
What is the role of this icon?

![pic_2018-12-20_200753](https://user-images.githubusercontent.com/15686075/50284193-33f66480-0493-11e9-8169-128a54bab7c2.png)

**Comment by q962** [comment]
Can the left 'project' column be hidden like the 'console' column?

**Comment by perborgen** [comment]
Hi @q962 !

just hit Esc to close the search tool. The Project column can unfortunately not be closed.

**Comment by q962** [comment]
I know
But the same version of the browser is valid under win7
Win10 is invalid
I am talking about the esc off search tool

The keyboard is not damaged ：）

**Comment by q962** [comment]
![image](https://user-images.githubusercontent.com/15686075/60229316-0b2eac00-98c8-11e9-83f5-fe7cf44aaa0f.png)

`div.BrowserFrame.frame` and `div.BranchesListView` Very bad location
