### ISSUE TITLE
Learning Paths Feature

### ISSUE THREAD

**Issue by AMVisionary** [scrimba/community#375]
Hi team,

I absolutely love Scrimba and the interactivity it brings to coding.

I'd like to request a feature with which the team can create learning paths to specific end goal, such as: "CSS Mastery".

This would then be populated by ordered courses to achieve that goal.

People can then create their own private learning paths etc.

Hope something similar to this could be implemented soon.

Thank you

**Comment by Pistus** [comment]
Thanks a lot,

We do have playlists and courses on topics like https://scrimba.com/g/ghtmlcss and https://scrimba.com/g/glearnreact. You can create your own playlists, so I think this covers the usecase you mention. So I will close this issue and hope you keep learning!
