### ISSUE TITLE
Stop/suspend "autoplay next video" when playground mode is enabled

### ISSUE THREAD

**Issue by Jeto143** [scrimba/community#376]
Oftentimes, when I watch a screencast, I like to go into playground mode at the end to well, play around with stuff I just learned about.

Now if you forget to hit "Cancel" on the bottom right thing, the following cast in the playlist will automatically start and cancel anything you've done. This is quite annoying.

So my suggestion would be to suspend the "auto play next" feature whenever you're in playground mode. (Sorry if that was already suggested, didn't find it.)

**Comment by davidferguson** [comment]
+1 for this. Just discovered scrimba today and really impressed by it, but this is an improvement I'd like to see.

**Comment by scanf** [comment]
👍 Also experiencing this issue. Would love to see it fixed 😄

**Comment by scanf** [comment]
This has now been fixed and will be deployed soon.

Thanks.
