### ISSUE TITLE
other spoken language

### ISSUE THREAD

**Issue by jorgeluisrezende** [scrimba/community#378]
Can I create courses in another language than english?

**Comment by eladcandroid** [comment]
I'm asking too.. about Hebrew language

**Comment by jorgeluisrezende** [comment]
It will be nice to grow other communities around the scrimba!

**Comment by perborgen** [comment]
Totally agree with you. The Scrimba frontpage will focus on English courses in the near future though, as we don't have the resources to spread our content creation efforts throughout multiple languages. However, it's free for whomever to create content on Scrimba, so we're more than welcome to see instructors creators create content here, and then share it with their communities.

**Comment by jorgeluisrezende** [comment]
@perborgen I'm very glad to known it, and i want to congrats you by the awesome work that you are doing here.
so i will close this issue now.
