### ISSUE TITLE
Main web page broken.

### ISSUE THREAD

**Issue by artejera** [scrimba/community#384]
Hi guys.   

Let me share that I'm enthralled by your react tutorial, really great ideas and best quality you have.  Congratulations.

One detail to improve is that if you see the main scrimba.com page with zoom not set to 100% in the browser, you easly lose the buttons to search topics right and left.  Tried in Chrome and Firefox (linux).

Cheers

**Comment by scanf** [comment]
The front page has changed since February.

Thanks.
