### ISSUE TITLE
shortcut for uncomments HTML/CSS on Mac does not work

### ISSUE THREAD

**Issue by tmoia** [scrimba/community#389]

**Comment by tmoia** [comment]
My uncomment shorcut "cmd + / " for HTM/CSS doesn't work. it opens the "help" of chrome. any idea to solve this? thanks

**Comment by scanf** [comment]
Justed tested it with recent Chrome (`Version 75.0.3770.100`) and it's working fine. Please reopen this issue if you can reproduce.

Thanks.
