### ISSUE TITLE
Deleting cast while viewing it leaves the deleted cast onscreen

### ISSUE THREAD

**Issue by CreaturesInUnitards** [scrimba/community#39]
Clicking the "edit" icon next to the Cast title below the code editor presents a dialog which provides for deleting the Cast. Clicking delete works, but UX is confusing because it doesn't appear to work until we navigate out. 

Suggest kicking the user out to the dashboard.

**Comment by scanf** [comment]
The UI has changed the last two years. Closing this. Please open up new issues if you are still experiencing issues.

Thanks.
