### ISSUE TITLE
Incorrect line number in JS error messages 

### ISSUE THREAD

**Issue by verheyenkoen** [scrimba/community#394]
I was playing [lesson 3 of the ES6 course](https://scrimba.com/p/p7v3gCd/cLez8TE) and noticed the demo shows an error message on line 11 while the error in the editor is actually on line 8. This probably has to do with preprocessing or something but I was thinking this can maybe be improved so the error message reflects what is in the editor. 

![image](https://user-images.githubusercontent.com/599538/53793262-c30d0780-3f2d-11e9-9529-d9ef8803b221.png)

**Comment by perborgen** [comment]
Yes, this is due to how we package the project under the hood. Thanks for reporting, but it's not something we'll focus on fixing at the moment unfortunately.
