### ISSUE TITLE
No sound on any tutorials

### ISSUE THREAD

**Issue by Raoch** [scrimba/community#396]
Hi,

I am not able to hear sound on any tutorial. Originally using FireFox Quantum 65.0.2 (64-bit) and later tried on Chrome Version 72.0.3626.121.

Thanks

edit: 
Just tried Microsoft Edge 44.17763.1.0 with no luck. Works on my Android phone Chrome broweser though.

**Comment by perborgen** [comment]
Which OS are you on?
