### ISSUE TITLE
Click event on slides wasn't recorded

### ISSUE THREAD

**Issue by ackzell** [scrimba/community#397]
Hello!

Thanks a lot for this platform. It is such a great idea and it blew my mind from the first time I saw it.

I am currently recording some videos, and so far has been great. Though right now I am facing an issue with one of my recordings where the click I made to open up the slides wasn't recorded and the slides won't come up on playback.

Is there a way to insert that click event after the fact? I could re-record but if there would be a chance not to, I'd rather do that 😅 

Thanks again and keep up the good work!

**Comment by perborgen** [comment]
Hey, it might be that you've interacted with the slides during playback (you can open and close the slides as a viewer during playback). In that case, try to refresh the browser and view the cast once more (without clicking on the slides to interfere with the playback) to see if it's actually working as expected. 

If this doesn't "solve" the problem, then you'll unfortunately have to re-record.

**Comment by ackzell** [comment]
Thanks for your answer @perborgen, seems like I will need to re-record then.

I figured as much, tried watching it a couple more times and then realised that in edit mode I can't see the event mark on the recording, this is why I asked. 

During playback the mouse pointer moves just as if I were pointing to the text in the slide, but it won't show up. Not a huge deal I guess... aim is that my videos are short.

Thank you again for enabling content creation this way!

**Comment by perborgen** [comment]
Thanks for your understanding, and sorry about the issue you experienced here. I'll close this issue then.
