### ISSUE TITLE
Create new courses

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#398]
Which ones?

**Comment by Yoshik18** [comment]
Please create a course on Node.js

**Comment by perborgen** [comment]
We unfortunately don't support Node.js in Scrimba.

**Comment by FrancoisGeyser** [comment]
Could you do a Python course?

**Comment by perborgen** [comment]
We can't do Python either, as Scrimba only supports client-side technologies (HTML, CSS, JS).

**Comment by perborgen** [comment]
I'm closing this, as we'll ask for feedback regarding courses in a more structured way.
