### ISSUE TITLE
Removing the "Resuming will erase your local changes. Are you sure?"

### ISSUE THREAD

**Issue by arashsa** [scrimba/community#4]
The popup window gets a bit annoying after a while. Would be better if the message was different. Maybe the play button has the "resume?" status once you press play after having played around with the code. I accidentally end up pressing the play instead of resume more often than not. 

A key combination to resume would be great, like CMD + Space.

**Comment by somebee** [comment]
Will do. Pressing play is a pretty explicit action, so I guess we don't really need the prompt at all. Maybe add a "click to go back to your local version" or something that pops up (without stealing focus) for 5-10 seconds after resuming.
