### ISSUE TITLE
Can't edit Playlist meta after it's created

### ISSUE THREAD

**Issue by CreaturesInUnitards** [scrimba/community#40]

**Comment by beaucarnes** [comment]
I would also like this feature.

**Comment by perborgen** [comment]
This is actually possible already. It's just a bit hidden. Just head over to your profile, and click on the three dots above your playlist to the right.



<img src="https://cdn.filestackcontent.com/F6L1Z6aFQNGVh2N6bdpu" width="1146" title="Screenshot 2019-04-10 at 08.39.55.png">

**Comment by beaucarnes** [comment]
Thanks!
