### ISSUE TITLE
JS ES6 is not supporting Spread Operator objects

### ISSUE THREAD

**Issue by fazurrehman** [scrimba/community#400]
Example this.
const user1 = {
    id: 1,
    name: 'faizur rehman',
    age: 26,
};

const user2 = {
    ...user1,
};

console.log('User:', user1);
console.log('User2:', user2);

I checked in codepen and it is working fine but in scrimba, its giving error 
Error: SyntaxError: unknown: Unexpected token (61:4) (/index.js:1)

**Comment by dorelljames** [comment]
I found this issue as well. You can temporarily use `.concat` function momentarily :)

**Comment by letoast** [comment]
Yeah, but not for objects. You have to use Object.assign() for that

**Comment by scanf** [comment]
Also noticed this when it was pointed out in the [Introduction to ES6+](https://scrimba.com/p/p4Mrt9/czMQdcM)

**Comment by perborgen** [comment]
We just deployed support for this one.
