### ISSUE TITLE
Next video should be auto play, when Play-next-video button clicked  

### ISSUE THREAD

**Issue by Civon** [scrimba/community#401]
## Now: 
when video ended, indicate dialog for next video in playlist will pop up and the progress circle running, till end windows will jump to next and stop playing.  **thats good**! 
But, if mouse click the play button in dialog, it act the same as above, which is not as expect  as a video watcher want to *"play"* next.

## Improve: 
Change the action of the play-button-clicked to **auto play next video**

Nice project!

**Comment by perborgen** [comment]
Hey, this one has been fixed, we're now auto-playing like YouTube.

**Comment by alexdobsom** [comment]
it's not working anymore with the new UI

**Comment by anburocky3** [comment]
It is not working now.

**Comment by gabrielpersaud** [comment]
here is a one line JS-injector script to trigger the play button. I'm using Scripty for chrome.
`document.querySelectorAll('div.tool.pb.blue.svg.play')[0].click();`
