### ISSUE TITLE
Improvement on click and preload

### ISSUE THREAD

**Issue by bofeiw** [scrimba/community#405]
Hey I've watched some tutorials on Scrimba and found a place where could improve user experience. 

### 1. After one section sends, I need to click two times to play next section.
I need to first click this at bottom right
<img width="576" alt="Screen Shot 2019-04-25 at 11 42 47 am" src="https://user-images.githubusercontent.com/34177142/56704192-8c928280-674f-11e9-9bf6-f9883ba2ea81.png">
and then click this on the centre of screen.
<img width="1506" alt="Screen Shot 2019-04-25 at 11 42 55 am" src="https://user-images.githubusercontent.com/34177142/56704193-8c928280-674f-11e9-85f3-8db12de70955.png">

#### I would suggest to preload all sections when first open that tutorial(Preload all 9 sections when opening Vue tutorial). The size of contents are small compared to videos, I assume that preloading all can happen.

**Comment by perborgen** [comment]
We've fixed this so that you only have to click once to play the next video (or wait, and it'll auto-play automatically)

**Comment by bofeiw** [comment]
> We've fixed this so that you only have to click once to play the next video (or wait, and it'll auto-play automatically)

How about the second one, preload all videos?

**Comment by perborgen** [comment]
We don't have capacity to fix that one now unfortunately.
