### ISSUE TITLE
Bug switching videos: autoplay force to redirect even selects another video 

### ISSUE THREAD

**Issue by bofeiw** [scrimba/community#406]
After one video ends, autoplay overrides the action of selecting another video. So when clicking another video at the end of one video, first the autoplay appears and immediately the page is redirected to the video clicked. But then the autoplay redirect once more, to the autoplayed video, which should not happen because Ive selected the video to play.

Its a bit hard to describe in words. Please watch this bug video for accuracy: [https://youtu.be/ebpjH4Sbv8k](https://youtu.be/ebpjH4Sbv8k)

**Comment by perborgen** [comment]
Hey, we've fixed this one now, as screencasts now autoplay like on YouTube.
