### ISSUE TITLE
Feature request: Scrolling the iframe when the video is playing 

### ISSUE THREAD

**Issue by bofeiw** [scrimba/community#407]
Currently, when I want to scroll the page displayed in the iframe (browser in broswer) when the video is playing, I need to click the rerun button and have the video paused to scroll the page. 

Wouldn't it be nice to enable scrolling while the video is playing? So I don't need to wait for the page to refresh and have the video paused.

**Comment by perborgen** [comment]
This is unfortunately not something we'll prioritize atm, so I'm closing this issue.
