### ISSUE TITLE
Strange behaviour with icon bar active states when reloading

### ISSUE THREAD

**Issue by ArsalaBangash** [scrimba/community#410]
https://scrimba.com/c/cR3ZBNhM

If you go to the last 10 seconds, the icon bar: 
        - Keeps the first 4 icons active when reloading 
        - Sometimes the first 3 icons are active
        - If you scroll through it, what you see is what you'd excpect to see

I've pasted the same code into codepen and it works fine so I believe this is a scrimba issue.

**Comment by perborgen** [comment]
Hmm... I get the first Icon being active when I run the code.

**Comment by perborgen** [comment]
It looks ok when you're playing it, right? Also, can you share the Codepen?

**Comment by ArsalaBangash** [comment]
Hi Per, 

This is the link to the codepen. https://codepen.io/arsalabangash/pen/pmRENZ

I may have figured out what's going wrong. I created another screencast to test over here: https://scrimba.com/c/cemnmJTa

It seems that the unexpected behaviour only shows up when you play the sequence twice. 
Steps to reproduce: 
1. Play the screencast
2. Pause a couple seconds before the cast finishes 
3. Play from the beginning 

Thanks! 
![scrimba410](https://user-images.githubusercontent.com/19757203/58259514-8df0a400-7d29-11e9-894c-1745ec90ac93.gif)

**Comment by perborgen** [comment]
So I think the root cause of this is how the Scrimba DOM-recorder works, since we're not actually recording pixels, but just events, and CSS animations can't be controlled on a frame-to-frame basis it's a bit tricky to 100% dictate how the mini-browser will look when rewinding. It's not something we're able to fix right now unfortunately.

**Comment by perborgen** [comment]
But I guess you can give people a notice in the beginning of the cast that if they start rewinding back and forth and the aminations look weird they'll just have to refresh the entire cast, and it should work normal again.

**Comment by ArsalaBangash** [comment]
Wonderful :)
