### ISSUE TITLE
how work scrimba ?

### ISSUE THREAD

**Issue by id1385** [scrimba/community#412]
i know you record events but how ?
i want make an site like u but i dont know you how record and play casts !

can u share scrimba recording script code ? or help how can create an site like u 
or any tools to help ...

**Comment by id1385** [comment]
I tried to see what you send to server on recroding cast.
i see an socket send encoded data 
`wss://scrimba.com/socket`
and what is this ? https://scrimba.com/rpc/streamRead
**I did not understand anything**

**Comment by perborgen** [comment]
Hi, Scrimba is not open source unfortunately. To understand the source code you'd also have to learn Imba first, which is the open source language @somebee has created, and built Scrimba with.
