### ISSUE TITLE
Scrimba is downed?!

### ISSUE THREAD

**Issue by 411A** [scrimba/community#413]
can't load the website & twitter account is deactivated.

**Comment by rokublac** [comment]
Today, the website has been throwing the occasional `502` error, but it is not completely down. I'll have a check with @perborgen and see what is going on.

As for the twitter, there has been a change in the twitter handle. It used to be **scrimba_com** but now it is. [twitter.com/scrimba](https://twitter.com/scrimba).

**Comment by rokublac** [comment]
The website stability seems to be back on track, so I think it should be all good now :thumbsup:
