### ISSUE TITLE
Preview during playback has redundant, incorrect output

### ISSUE THREAD

**Issue by CreaturesInUnitards** [scrimba/community#42]
repro might be weird — if collaborators can see my Drafts, please look at the output at the end of the cast called "Weird, Redundant Output". Then manually run the code and you'll see the correct output.

**Comment by somebee** [comment]
Investigating this now. The mithril renderer produces some surprising dom mutations in many cases, so it probably triggers an edgecase we haven't accounted for in our recorder (which tries to register needed mutations in an optimised way). Will keep you posted.

**Comment by somebee** [comment]
Fixed and deployed now. The bug was triggered when there are mutations nested inside a dom-node that was itself inserted in the same batch of mutations (coming from MutationObserver). Pretty major flaw in our recorder, so thanks for reporting!

**Comment by CreaturesInUnitards** [comment]
Dude! Thanks for being so responsive!
