### ISSUE TITLE
macOS Safari: Screencasts sometimes do not begin/resume correctly when using AirPods

### ISSUE THREAD

**Issue by purrloftruth** [scrimba/community#423]
Observed the other day using Safari 12.1.1 on macOS Mojave 10.14.5; apologies that I wasn't able to report until now.

I'm unsure if this is an issue with all bluetooth headphones (which I would suspect) or just AirPods (which I would find unlikely), but I don't have other bluetooth headphones to test with right now.

Sometimes, when I have my AirPods connected, and I click the initial play button or the bottom-left play button to either begin or resume the screencast, instead of beginning to play, the button in the bottom-left will change to a spinner. Sometimes, after several further attempts at pausing and unpausing, playback will begin, but this results in an audio track that is desynced from the editor playback (it will be as if the audio track has been playing for the entire time that the spinner has been displayed).

This does not happen reliably every time (but does happen reliably enough to be annoying); often, reloading the page has a chance of fixing the issue, though it may come back about later if the screencast is paused (and an attempt to unpause is made) at a later time.

As macOS handles audio-video synch when listening on bluetooth outputs at the operating system level (as I understand it), I'm unsure if the behavior would be different in other browsers -- I haven't yet tested to check.

**Comment by rokublac** [comment]
If you're able to test it on another browser and let me know how it goes, that'll be great. 

I'll also have a test on my end with your specifications with one of my bluetooth headphones and see how it performs.

**Comment by purrloftruth** [comment]
I wasn't able to reproduce in Google Chrome 77.0.3833.0 or Firefox 68.0, at least by intentionally trying to do so. I think the original bug in Safari might have to do with playback beginning when no audio has been playing out of the connection for some time and it goes into a suspended state; it takes a few refreshes for Scrimba to be able to play the audio, but then it will reliably play whichever screencast I go to as long as I do so within a quick period of time. (When I have not been able to resume after pausing, it has always been after the screencast has been paused for a significant amount of time.) I think perhaps Safari uses a different (more macOS-native?) method of interfacing with the sound system -- since it seems to have some knowledge that a bluetooth connection is involved (I suspect it may be the same for other wireless audio connections such as AirPlay, which Safari also has in-built support for with HTML5 audio/video tags).

I primarily use Scrimba in Safari, so I'll comment further if I gain any further insights into the nature of the bug beyond what else I've posted here.

**Comment by rokublac** [comment]
I tested it with my bluetooth headphones and things seem to okay while testing, but I'll keep my eyes out if anything bugs out in the future on these specs. I'm not sure if you have any extensions installed, but some are known to interfere with Scrimba's performance.

**Comment by scanf** [comment]
I am closing this for now, please reopen if you experience any more issues. Thanks.
