### ISSUE TITLE
Watch & listen to a recording before committing it to the screencast

### ISSUE THREAD

**Issue by CreaturesInUnitards** [scrimba/community#43]
the authoring workflow absolutely must include the ability to review the just-completed recording before it is merged into the current screencast.

**Comment by somebee** [comment]
I am currently working on much improved post-processing which lets you restart recording from any position, and also collapse / trim any part of the timeline after recordings. We will also now generate a single published audio track (however many different recordings and edits you have), which makes loading and playback much smoother (we've been having issues with out-of-sync audio etc in the current version). You will also be able to silence parts of the audio recordings if need be.

I'm confident that we will be able to deploy it this coming weekend. Just wanted to let you know that a better workflow is underway :)

**Comment by CreaturesInUnitards** [comment]
@somebee Outstanding! I look forward to picking it apart 😜

**Comment by somebee** [comment]
The original request should have been rectified by recent improvements to the recording flow, since you can now re-record from any position in the timeline. Closing :)
