### ISSUE TITLE
[Bug]: Remove `overflow: hidden` from `.SpaceDrawer pre` CSS rule

### ISSUE THREAD

**Issue by bobziroll** [scrimba/community#430]
This way people can scroll through `pre` code in the comments.

![ScreenRecording2019-07-20at1](https://user-images.githubusercontent.com/6244647/61583692-a0544780-aaf8-11e9-9455-e777406f970a.gif)

**Comment by perborgen** [comment]
We'll look into this one next week.

**Comment by perborgen** [comment]
Fixed
