### ISSUE TITLE
[feature-request]: support for running node modules that require filesystem access

### ISSUE THREAD

**Issue by scanf** [scrimba/community#434]
Hei,

I was planning on doing a screencast about [Squidex][0], my NPM module [squidex-client-manager][1] and possibly it's dependencies require filesystem access. When I try to use it I end up with the error below  (example https://scrimba.com/c/cnZydVcZ)

```
Error: Unknown require: fs (in module /node_modules/squidex-client-manager/src/index.js) (/node_modules/squidex-client-manager/src/index.js:1)
```

[0]: https://squidex.io
[1]: https://github.com/scanf/squidex-client-manager

**Comment by perborgen** [comment]
We don't support server-side code unfortunately, so this won't work yet.
