### ISSUE TITLE
Edit Profile

### ISSUE THREAD

**Issue by fleuronvilik** [scrimba/community#440]
After opening a Scrimba account with my Github account, I change my username on Github. I also want to change my username or other personal information on Scrimba. But, the platform currently provides no way to achieve this. Or I don't know it.

My second concern is the ability to log in using both Github and E-mail / Password.

Thank you.

**Comment by scanf** [comment]
Someone just asked about this on Slack so replying same to you. Unfortunately this is currently not supported yet but you can email @perborgen on [per@scrimba.com](mailto:per@scrimba.com) and he should be able to help you.

**Comment by fleuronvilik** [comment]
Thank you @scanf.
