### ISSUE TITLE
home page not working

### ISSUE THREAD

**Issue by droidgoo** [scrimba/community#441]
going to https://scrimba.com/ in firefox 60.8.0 yields a mostly non-working landing page.

clicking on 1 does nothing
clicking on 2 button reacts to hover but nothing else happens
clicking on 3 takes me to a non-working version of the course start page.

![Capture](https://user-images.githubusercontent.com/54815770/64129254-feb74b80-cd6f-11e9-98ac-fc3e178d80ed.JPG)

however, if i scroll all the way to the bottom and click on "about", then now item 2 works and I can login/see my profile.

also from the "about" page, item 3 takes me to a WORKING version of the course start page.

still having playback issues with the course, but that's probably a different problem.

**Comment by droidgoo** [comment]
accessing the site from the current Opera browser now, and everything seems to work as expected... i have not tried re-installing FF, and i'm not likely to as it works fine with everything else i do on the web.

**Comment by scanf** [comment]
This should now be resolved, confirmed it's working fine in `60.8` and `60.9`. Let us know if you are still encountering the issue.

Thanks.

**Comment by droidgoo** [comment]
Thanks, the login issues seem to be resolved... however, as i mentioned at
the end of my write up

"still having playback issues with the course, but that's probably a
different problem."

should i start another ticket for this problem?


anything after the first couple of videos will play audio, but the video
hangs at about 95% in the progress bar and never appears during the
playback.. i just get this on my screen the whole time.


[image: Capture.JPG]

**Comment by scanf** [comment]
@droidgoo please create a  new issue https://github.com/scrimba/community/issues/new

Thanks.
