### ISSUE TITLE
JavaScript template strings syntax highlighting not working

### ISSUE THREAD

**Issue by bobziroll** [scrimba/community#449]
I just noticed this in the React Hooks course:

<img width="655" alt="Screen Shot 2019-10-02 at 11 05 24 AM" src="https://user-images.githubusercontent.com/6244647/66065867-9477ff00-e505-11e9-913a-d5e5e5d34604.png">

I haven't tried recreating it on my own though, so I apologize if it's a one-off issue.

**Comment by scanf** [comment]
I have tested this and can confirm it will be resolved when we upgrade our monaco version and theme.



Thanks.
