### ISSUE TITLE
FeatureRequest: Correct pitch/ tone on playback speed change (Like youtube et al)

### ISSUE THREAD

**Issue by blueeyes08** [scrimba/community#453]
When you choose a faster pace on the playback voices are not autopitch/tone adjusted, as they are in e.g. Youtube, leading to an "unpleasant voice experience"
not sur exactly what audio plugin could solve this, but doubt it would be a huge programming job.
( i couldn't find how to add the labels, but this is a feature enhancement request)

**Comment by perborgen** [comment]
Hey, this only happens when you watch your own tutorials. Try watching your tutorial from an incognito browser and you'll notice that the pitch is fine.
