### ISSUE TITLE
Mini browser not working after making changes.

### ISSUE THREAD

**Issue by squiddie** [scrimba/community#457]
The mini browser stays completely white after:

- Pausing the video.
- Making changes.
- Refreshing the mini browser.

It's reproducable and actually never worked for me (this is my first day thogh).
It affects all courses I tried.

<img width="1200" alt="minibrowser" src="https://user-images.githubusercontent.com/23278/66948839-bcaf4400-f055-11e9-8ac8-e31a20202572.png">

**Comment by perborgen** [comment]
Which browser are you using @squiddie ?

**Comment by squiddie** [comment]
@perborgen I'm using Firefox. I tried it on a different machine also running Firefox and it works there.

**Comment by perborgen** [comment]
Ok, which version didn't it work with @squiddie? It's likely because that Firefox version doesn't support Service Workers.

**Comment by squiddie** [comment]
They're both most recent 69.0.3. Same plugins (Dark Reader, uBlock Origin, vue.js devtools). Tried deactivating uBlock without success.

**Comment by squiddie** [comment]
MS Edge doesn't work either. But. When I have the same page opened in both browsers and I make changes in Edge I can immediately see them in Firefox. That's for the document. The mini browser doesn't work in both.

**Comment by squiddie** [comment]
@perborgen It's working now. No changes made on my side. This also resolved my yet unreported issue that images were not displaying. Please close.

**Comment by ZeddZoul** [comment]
I am using Brave browser and i have the same issue

**Comment by HookdaCode** [comment]
im using opera gx and i have the same issue. Sometimes its working, but 80% its not.
