### ISSUE TITLE
Paid course teaser not embed friendly

### ISSUE THREAD

**Issue by Pistus** [scrimba/community#458]
Found an embed, and it shows the bootcamp teaser after playing - but it is broken in this size.

![Screenshot 2019-10-25 at 12.10.09.png](https://gitspeak.com/-/nUp3bjL39f851/Screenshot%202019-10-25%20at%2012.10.09.png)

**Comment by scanf** [comment]
This issue seems to be outdated, please reopen if that is not the case.

Thanks.
