### ISSUE TITLE
Richer metadata (links/notes)

### ISSUE THREAD

**Issue by CreaturesInUnitards** [scrimba/community#46]
Ideally, below the code window, we would see a list of relevant links and/or any other notes from the author

**Comment by CreaturesInUnitards** [comment]
I don't think we necessarily have to feature a full HTML or markdown editor; we could probably list links first with fields for URL, Link text, and quick description,  followed by a general notes area.

**Comment by perborgen** [comment]
Markdown editor will be added to the next deployment :)

**Comment by Pistus** [comment]
Closing as stale issue.
