### ISSUE TITLE
Mini browser not Rendering

### ISSUE THREAD

**Issue by IamDarkLord007** [scrimba/community#460]
I am having issue, when I enter the playground mode and run my code or just change anything in your code, the little browser doesn't render it. Is it because of the root directory ? it shows "/" for file location in browser.

I hope it gets fixed. Thank You

**Comment by Dulfite** [comment]
I am also having this issue.

**Comment by scanf** [comment]
@Dulfite can you reproduce it reliably? Even better if you have a playground.

Thanks.

**Comment by mczandre** [comment]
Same issue here... By the time I change anything on the code, the mini browser no longer reflect my changes.
I tested several alternatives such as different browsers with and without ad blockers.

**Comment by perborgen** [comment]
Next step: notify Sentry when this happens.

**Comment by scanf** [comment]
Hopefully getting a fix for this soon. It took a while to be able to reproduce it reliably 😅

@mczandre I think the issue you are facing might be slightly different. Could you open up a new issue? Thanks 🙏🏾
