### ISSUE TITLE
Horizontal scrolling glitches in Chrome and Firefox (worse in Chrome)

### ISSUE THREAD

**Issue by bobziroll** [scrimba/community#461]
See attached gifs. 

In Chrome, it gets stuck partway in the scroll visually, but clicks act as if the scroll had completed. (Clicking the small gear icon to edit a cast actually opens the cast because the icon's location is different from where it appears to be.

In Firefox, the scroll completes, but "catches" halfway through each time.

In Safari, the scroll is smooth and acts as expected.

### Chrome:
![scrimba_scrolling_issue_chrome](https://user-images.githubusercontent.com/6244647/68039799-864b0900-fc92-11e9-9716-720e924e3519.gif)

### Firefox:
![scrimba_scrolling_issue_firefox](https://user-images.githubusercontent.com/6244647/68039810-8ba85380-fc92-11e9-805f-5ca1211a7ba9.gif)

### Safari:
![scrimba_scrolling_issue_safari](https://user-images.githubusercontent.com/6244647/68039821-9236cb00-fc92-11e9-8f32-34c3a1b28d88.gif)

**Comment by scanf** [comment]
A overwhole of the design is in progress, closing this.

Thanks.
