### ISSUE TITLE
Add React.Fragment linting support

### ISSUE THREAD

**Issue by bobziroll** [scrimba/community#462]
React's shorthand for Fragments allows for empty tags `<>` and `</>`. In Scrimba's editor they show as syntax errors. (They work as expected in the mini browser and throw no actual errors). See screenshot.

<img width="544" alt="Screen Shot 2019-11-01 at 10 34 24 AM" src="https://user-images.githubusercontent.com/6244647/68040183-5e0fda00-fc93-11e9-8e78-f3f360c86db1.png">

**Comment by somebee** [comment]
This should now work :)
