### ISSUE TITLE
React Router nested route breaks app

### ISSUE THREAD

**Issue by bobziroll** [scrimba/community#469]
Nested routes by themselves are working fine, but if you try to refresh the mini browser while on a nested route, Scrimba throws an error and the app breaks. See gif below.

![Nested routes issue](https://user-images.githubusercontent.com/6244647/70659955-5a6e5c00-1c1e-11ea-8502-cc9aedffac56.gif)

**Comment by bobziroll** [comment]
Sorry the gif is so slow... online converter did that...

**Comment by scanf** [comment]
I will take a look at this, thanks for adding steps to reproduce 🙏

**Comment by somebee** [comment]
@perborgen@bobziroll https://scrimba.com/c/cLpVNycy

**Comment by bobziroll** [comment]
@somebee I'm still having the same problem with that link. Is there something different I should be looking for?

**Comment by rokublac** [comment]
> @somebee I'm still having the same problem with that link. Is there something different I should be looking for?

Hey @bobziroll, 
Adding a forward slash in front of `index.pack.js` and `style.css` in my top level html, it seems to be working on my end. Though, I didn't try it on the exact cast in the referenced GIF, but your other casts with nested routes seem to work okay.

Are you still getting the error after doing this?
