### ISSUE TITLE
"cancel" button sometimes acts like "finish"

### ISSUE THREAD

**Issue by CreaturesInUnitards** [scrimba/community#47]
Difficult to reliably repro, since I haven't seen much of a pattern of when it happens, but several times I've tried to kill my current recording by hitting ```cancel``` and instead it gets committed.

It _does_ seem to happen more often on longer recordings, but that may or may not be related.

**Comment by somebee** [comment]
This is one of many issues that will be solved by the overhaul mentioned in #43 :) I'm now confident that I will *not* be able to ship it this weekend, sadly, but sometimes next week instead. It is a pretty big update that also lays the groundwork for annotations and other cool stuff. Looking forward to getting it into your hands :)

**Comment by CreaturesInUnitards** [comment]
No worries! I'll just stop making new recordings until the new bits drop, then; TBH it's pretty frustrating in the current state. I'm really excited about the overhaul! Thanks again for all your hard work.

**Comment by somebee** [comment]
I absolutely agree. I'm having a hard time recording things myself. With the new editing tools it's _much_ better :) Thanks again for creating great content and showing so much interest! It is very motivating!

**Comment by perborgen** [comment]
This should be fixed by the latest deploy, so I'm closing this one.
