### ISSUE TITLE
Customizable Note Title

### ISSUE THREAD

**Issue by rokublac** [scrimba/community#471]
> Hi all. Scrimba is an outstanding learning tool. I'm really enjoying it. I would love to see the ability to edit the title of notes made during Scrimba lessons. This would make navigating notes much more intuitive. Currently a default title of 'Local edits at...' is generated whenever the user interacts with the coding area, but this title doesn't mean much when you are coming back to revise notes at a later date. Would this be possible?

by @gerardsargent 

https://spectrum.chat/scrimba/bugs-and-issues/feature-request-customised-note-titles~00b1a818-30c6-4f29-ba6d-29853f227cab

**Comment by perborgen** [comment]
Hey @gerardsargent  ou can customize your Notes' titles on the My Notes page.
