### ISSUE TITLE
Download .zip failing

### ISSUE THREAD

**Issue by petonagy** [scrimba/community#472]
Hi Guys!

Thanks for creating scrimba, it's a great way to learn and practice.
I have a problem with downloading a .zip archive from the lesson. It ends on cloudflare Error 520.

Thanks.

**Comment by perborgen** [comment]
I think this one was fixed yesterday, wasn't it @scanf ?

**Comment by somebee** [comment]
This is fixed

**Comment by petonagy** [comment]
Yes, fixed, thanks :)
