### ISSUE TITLE
Microsoft Edge - Invisible typing in Sign in input

### ISSUE THREAD

**Issue by rokublac** [scrimba/community#473]
> When you click on input : the placeholder stays and letters are invisible when you type. - [via Spectrum](https://spectrum.chat/scrimba/bugs-and-issues/microsoft-edge-login~c29919ee-1bbb-4935-80d8-7b78790a80b7) @olivvv59

![Microsoft Edge Sign-in Bug](https://media.giphy.com/media/ZYR1mlKEotvnPiMhlV/giphy.gif)

Bug was reproduced on Microsoft Edge v44.18362.449.0

**Comment by scanf** [comment]
This is likely due to Edge not supporting `:placeholder-shown`, https://caniuse.com/#search=%3Aplaceholder-shown

We can fix this by changing that out in Edge.

**Comment by scanf** [comment]
Please use the latest version of Microsoft Edge http://microsoft.com/edge

Thanks.
