### ISSUE TITLE
Page bug - Learn basic JavaScript Course

### ISSUE THREAD

**Issue by rokublac** [scrimba/community#474]
> **Learn Basic JavaScript - Page bug**
> Hi, I tried signing up to the above mentioned course (https://scrimba.com/g/gbasicjavascript) but I am unable to click the "Enroll for Free" button.
> 
> I can see the following JS error in the console (Chrome 78.0.3904.108):
> 
> "Uncaught (in promise) TypeError: Cannot read property 'avatarUrl' of undefined"...

Issue by @gaturro1984 via [Spectrum](https://spectrum.chat/scrimba/bugs-and-issues/unable-to-enroll-to-learn-basic-javascript~4cf84a25-527b-4b03-8ed6-e96e2197c554)

![Page bug](https://media.giphy.com/media/Ka2AoR89civOJBf38n/giphy.gif)

I did a test on **Chromium: 79.0.3945.88** and it seems to be functioning as intended only when I am logged in. If I'm logged out, some buttons become unresponsive. But for @gaturro1984, the issue happens in both scenarios.

**Comment by perborgen** [comment]
Oh, thanks for notifying us! Can you try again now? I think I fixed it.

**Comment by rokublac** [comment]
> Oh, thanks for notifying us! Can you try again now? I think I fixed it.

Thanks, all good for me now!
