### ISSUE TITLE
When the window is resized and when computer loses internet connection

### ISSUE THREAD

**Issue by hassanswifa** [scrimba/community#475]
I have been using Scrimba  for couple days, real awesome editor but I have noted that,

1. If you are coding and accidentally losing internet connection without notes, once you gain access, all of those running/executing command you have been trying, the mini browser will keep executing one after another unless you refresh.

2. Am using Mozilla Firefox and Google Chrome, one you resize the window, the editor doesn't work. I think, maybe  mini browser overflow because  itself is responding

**thank you**

**Comment by scanf** [comment]
Fix coming soon, thank you.
