### ISSUE TITLE
Scrimab site not working

### ISSUE THREAD

**Issue by midosamidos** [scrimba/community#476]
There is a problem with scrimba.com
can't sign in (Incorrect email/password), can't reset the password (no such email), all courses page in empty

<img width="1330" alt="Screenshot of Safari (08 01 2020, 04:38:38)" src="https://user-images.githubusercontent.com/16469219/71943229-fd3fd900-31d0-11ea-8c29-92e4969c62cc.png">

![Screenshot of Google Chrome (08 01 2020, 04:47:38)](https://user-images.githubusercontent.com/16469219/71943555-15642800-31d2-11ea-901c-b7b5fe376340.png)

**Comment by rokublac** [comment]
Is this still an issue for you? There were some website instabilities earlier in the day which could of causes this issue but it is gaining some stability as we speak so your problem might have been fixed.

**Comment by midosamidos** [comment]
> Is this still an issue for you? There were some website instabilities earlier in the day which could of causes this issue but it is gaining some stability as we speak so your problem might have been fixed.

I can confirm that it's working now with no problems.
Thank you
