### ISSUE TITLE
Create your own template

### ISSUE THREAD

**Issue by gre** [scrimba/community#48]
it would be great to be able to create a template. Or maybe more simply, if it was possible to fork a cast from another, is it even possible? just so you don't always have to re-configure all the scripts

**Comment by perborgen** [comment]
Hey, forking is possible yes. Just open up the cast, hit 'Edit code' and then 'Fork'.

**Comment by gre** [comment]
oh cool!

After creating a new Cast, is there any reason I can't see Edit Code (yet?)? is it because it's my own or maybe because it's not yet "recorded"/published ?

**Comment by perborgen** [comment]
Yes, it's because you haven't done a recording yet. We should probably give the opportunity to fork regardless of this, but right now you can just 'hack it' by doing a 1 second recording and then hit 'Edit code' -> 'Fork'.

**Comment by gokatz** [comment]
So, is it not possible to create our own template yet?

**Comment by rokublac** [comment]
> So, is it not possible to create our own template yet?

Sorry for the delayed reply. Refer to the GIF below on how to create your own template.

Note that you can delete the original cast that the template is based off and the template will still exist.

![create a template](https://media.giphy.com/media/UvWg43HwNbeucBDt5V/giphy.gif)
