### ISSUE TITLE
Notes not saving

### ISSUE THREAD

**Issue by SouthpointLtd** [scrimba/community#489]
I have been following along with the Learn React JS course and have been saving my notes successfully up until now. I have just re-written lost work from yesterday and still it is not saving my progress. I have lost another session of work. Very disappointed now having been super impressed before! Please help.

**Comment by perborgen** [comment]
@SouthpointLtd thanks for creating the issue. As I asked on Discord: could you share a screenshot of how it looks on your end when you're trying to share a Note?

**Comment by SouthpointLtd** [comment]
Hi Per,

So this morning the problem persists.

Screen 1: Adding the useState Hook to my Note and saving.

[A screenshot of a cell phone  Description automatically generated]

I am able to rejoin lesson and then review this code again. But, as soon as I refresh the browser window I lose all my changes. Please note that it has reverted back to the original first save. The timestamp does not change to reflect the latest save either.

[A screenshot of a cell phone  Description automatically generated]

Hopefully this is clear enough.

Robert Williams
Southpoint Solutions Ltd.

**Comment by perborgen** [comment]
Hi, this has been fixed, closing the issue.
