### ISSUE TITLE
Shortcut for running scripts.

### ISSUE THREAD

**Issue by arashsa** [scrimba/community#5]
Would be a nice addition to be able to run scripts automatically with a shortcut (cmd/ctr + enter).

**Comment by somebee** [comment]
cmd + b :)

**Comment by arashsa** [comment]
hehe, great! :)

**Comment by perborgen** [comment]
Done :)

**Comment by tmoia** [comment]
my uncomment shorcut  "cmd + / " for HTM/CSS doesn't work. it opens the "help" of chrome. any idea to solve this. thanks

**Comment by rovaelion** [comment]
Or Ctrl+S in Windows

**Comment by tmoia** [comment]
I m on mac but I have a Spanish keyboard. Maybe it is the problem.

**Comment by sga91** [comment]
cmd +b does not work for me
