### ISSUE TITLE
setSelectionRange bug for number inputs

### ISSUE THREAD

**Issue by JAForbes** [scrimba/community#50]
If you render a number input and select the value, the embedded web view will become unresponsive.  I believe there's some code accessing `setSelectionRange` on the input, but that method can't be used on a number input.

> Uncaught DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.

**Comment by somebee** [comment]
Thanks for reporting. Fixed now in our dev-branch. Will notify when deployed :)
