### ISSUE TITLE
Browser window is overlapped with the right sidebar

### ISSUE THREAD

**Issue by bchooxg** [scrimba/community#502]
![image](https://user-images.githubusercontent.com/56596358/83958853-1dbbae80-a8a9-11ea-9c4f-4f77466a3e61.png)

Browser window is always loaded to the right and is always overlapped with side bar

Every time a new video is loaded, the window would have to be dragged into view or sidebar has to be closed

**Comment by perborgen** [comment]
Hey. You can close the sidebar by clicking the > icon in its top left corner.
