### ISSUE TITLE
Video Pausing halfway throug

### ISSUE THREAD

**Issue by BarnaclesOnABoot** [scrimba/community#504]
Hi,

I'm doing the intro to javascript course and for some reason on this class, [here](https://scrimba.com/p/pPPeCy/cBzQ7DCL), it keeps freezing halfway through. 

Just thought you'd like to know.

Thanks,

Tom

**Comment by perborgen** [comment]
Thanks for reporting this, it was a bug, so we've replace the cast with a new one: https://scrimba.com/p/pPPeCy/cPkvD4tZ
