### ISSUE TITLE
module.exports behaviour unclear

### ISSUE THREAD

**Issue by JAForbes** [scrimba/community#51]
I've found only the `exports.x = ` syntax seems to work, but not the `module.exports = { x }` syntax.

It'd be great to get a fix / explanation of this behaviour.

**Comment by perborgen** [comment]
We're going to create more documentation in this repo soon. This will be covered. Please let us know if you have other subjects you think we should include as well.

**Comment by perborgen** [comment]
Hey, check the docs, I've added a point about this:

https://github.com/scrimba/community/blob/master/DOCS.md
