### ISSUE TITLE
Mark courses as "Completed" on "My Courses" page.

### ISSUE THREAD

**Issue by drumrock** [scrimba/community#517]
Now all courses that I'm enrolled to are shown as "Enrolled". Even those which are 100% completed.

They should be marked as "Completed" on "My Courses" page too.

![image](https://user-images.githubusercontent.com/10419376/87677549-90f6f100-c782-11ea-9dbf-ae34d174e4a3.png)

**Comment by Pistus** [comment]
Closing this as yteh site was re-built in the meantime:)
