### ISSUE TITLE
Volume Control

### ISSUE THREAD

**Issue by d3ddd** [scrimba/community#53]
I couldn't find a volume slider anywhere. 

My external monitor setup makes it difficult for me to change the master volume of my speakers so I heavily rely on being able to change the volume of videos I'm watching. That functionality seems to be missing from Scrimba.

**Comment by somebee** [comment]
It's coming with the next update :)

**Comment by perborgen** [comment]
This feature has been deployed in the latest update, so I'm closing this issue.
