### ISSUE TITLE
problem on course complete and later..

### ISSUE THREAD

**Issue by shante90** [scrimba/community#531]
You have problem on the site. When I completed a course,(it said 100% completed), I didn't fully understand a topic and I went back to the screencast. I went there and understood the topic. When I returned to content page, It showed 103% completed which is ridiculous. So, I complained because when new learners come if they see such thing, they may think that developers couldn't solve such small issue, then how could they help me learning my stuffs. This is about the reputation and image of the site . Just telling because I as a learner was shocked to see such problem( say 'bug') .

**Comment by Pistus** [comment]
Closing this as we redid the whole site since this.
