### ISSUE TITLE
Profile, Completed Courses incorrect

### ISSUE THREAD

**Issue by ramz35** [scrimba/community#542]
for me, it lists all courses whether completed or not.  No a huge issue for me personally as I know what I have or haven't done :)

**Comment by Pistus** [comment]
Yeah, we made it with the intention of separating the courses but the job was never done so the headline did not reflect the content. The profile page was actually removed, and you can now see the completed and active courses in the site header - or all courses in your dashboard.

**Comment by ramz35** [comment]
although on a mobile device the dashboard, courses lists only half of the course details (not properly responsive). I put this in discord and no biggie for me but for a front end developer and responsive focussed product it feels an odd bug to have (saying this as a subscribed member)
