### ISSUE TITLE
Homepage, 'Choose your next skill' - no way to scroll across courses

### ISSUE THREAD

**Issue by ramz35** [scrimba/community#543]
![image](https://user-images.githubusercontent.com/26057149/93665696-ed270b80-fa78-11ea-969d-49dbda865787.png)

On home page, there is no horizontal scroll bar to view the rest of the skills.

But there is in the My Profile section:

![image](https://user-images.githubusercontent.com/26057149/93665742-4ee77580-fa79-11ea-956b-751a6f49e118.png)

**Comment by Pistus** [comment]
Yeah, that carousel was causing some issues - so we removed it!
