### ISSUE TITLE
Can't play back my own casts in Safari

### ISSUE THREAD

**Issue by CreaturesInUnitards** [scrimba/community#55]
If I'm logged in, the play button doesn't work for my own screencasts.

Safari Version 10.1 (12603.1.30.0.34)

**Comment by somebee** [comment]
Thanks for reporting. Will get right on it :)

**Comment by somebee** [comment]
Should be fixed now, if you refresh :) Might take some time to load the first time you look at a cast of your own, since the server will create .m4a versions of the audio files for said cast.

**Comment by CreaturesInUnitards** [comment]
Thanks! I have a new one for you...
