### ISSUE TITLE
ABLE TO ACCESS PAID COURSES WITHOUT SUBSCRIPTION

### ISSUE THREAD

**Issue by mrskodi** [scrimba/community#555]
Hello, I BELIEVE THIS IS A HUGE BUG which needs to be taken care of as soon as possible! I am able to access 6 (not all) of the courses which are available only to paid members (with subscription). While browsing through the courses offered, I wanted to get a preview to 'The tricky parts of JS'. Interestingly, I could access them all. I DO NOT HAVE A SUBSCRIPTION and have never bought that course. Hope you are able to address this soon!

**Comment by Pistus** [comment]
Thanks for reporting this @mrskodi and appologies for lack of feedback. We did an update to the privacy settings of a lot of courses in December and I think this should not be an issue anymore. Please re-open the issue if that is not the case.
