### ISSUE TITLE
README tells me to apply labels to issues I file, but...

### ISSUE THREAD

**Issue by CreaturesInUnitards** [scrimba/community#56]
...since I'm not a contributor or collaborator, I can't apply labels.

**Comment by perborgen** [comment]
Ah, I wasn't aware, sorry about that, I'll look into how we can fix it.

**Comment by CreaturesInUnitards** [comment]
If there's no Github-sanctioned way to do it, I'd suggest something low-fi like following the issue title with the intended label in square brackets, e.g.

> **README tells me to apply labels to issues I file, but... [bug]**

**Comment by perborgen** [comment]
I've updated it so that the labels are added by us internally after they've been created.
