### ISSUE TITLE
Unable to delete scrims

### ISSUE THREAD

**Issue by Javiani** [scrimba/community#562]
Hi guys!

I'm just reporting a issue I saw in the scrimba dashboard. I created some scrims for testing, but I'm not able to remove any of them. It shows me a dialog asking if I really wanna delete it, I hit ok but nothing happens... I'm still with 7 scrims I can't delete.

I'm not sure if I'm doing something wrong...

Thanks in advance!

**Comment by Pistus** [comment]
Hi, thanks for reporting this and sorry for lack of feedback. We did an update in December that should have fixed this issue and your deleted scrims should now have been removed. Please re-open the issue if that is not the case.
