### ISSUE TITLE
GitHub auth from `Reset Password` modal doesn't work

### ISSUE THREAD

**Issue by pederjohnsen** [scrimba/community#573]
The one in the `Sign In` modal with url `/auth/github?from=/` works fine:
![working_github_button](https://user-images.githubusercontent.com/1238485/103482368-65bb9900-4dd8-11eb-8b9d-82b6bf230cd3.jpg)

but the one in the `Reset Password` modal with url `/login/subscriber` doesn't:
![non_working_github_button](https://user-images.githubusercontent.com/1238485/103482376-70762e00-4dd8-11eb-9c9b-3047dd8fe761.jpg)
![non_working_github_auth](https://user-images.githubusercontent.com/1238485/103482377-71a75b00-4dd8-11eb-973a-9c1b3f0bdb9e.jpg)

**Comment by Pistus** [comment]
Oh, that last url doesn´t make sense so no wonder it doesn´t work. Updated the Reset Password modal to use the correct url. Thanks for reporting!
