### ISSUE TITLE
Need a "Revert" option in non-recording mode

### ISSUE THREAD

**Issue by CreaturesInUnitards** [scrimba/community#58]
Changes to code can be saved without an active recording, but the only way to undo them is to refresh the page.

**Comment by perborgen** [comment]
Thanks for submitting this request @CreaturesInUnitards ! I'm curious to get to the bottom of it.  Is it so that *normal regret* (cmd + z) doesn't do the trick?

**Comment by CreaturesInUnitards** [comment]
@perborgen (cmd + z) works for text edits, but of course that can be time consuming and frustrating if the author does a lot before realizing they've gone down a wrong path. Also there's no way to undo file creation, although that could be handled if you implement #37.

**Comment by somebee** [comment]
This will be taken care of in the next release :)

**Comment by perborgen** [comment]
Closing this issue as this is now possible :)
