### ISSUE TITLE
Platform (SCRIMBA) doesn't work 

### ISSUE THREAD

**Issue by matteoceredi** [scrimba/community#598]
Dear all,

<img width="1440" alt="Screenshot 2021-05-19 at 19 35 30" src="https://user-images.githubusercontent.com/84496707/118951652-2c349600-b953-11eb-9c2c-9f1afdb922a1.png">

When I'm coding through the scribe platform at the front-end developer career path and I want to run a code as a result it appears on the window where I should see the result of the code a sentence like this : Either there’s a tear in the matrix or the page you’re looking for no longer exists.

I tried to move on with other modules but it's the same outcome, everything is working on my laptop so I don't understand the issue.

Please find the screenshot attached at the end.

I look forward to hear from you and thank you in advance.

**Comment by Pistus** [comment]
Sorry about that - this was a dns misconfigration I did when setting up a new environment.
