### ISSUE TITLE
Errors in script prevents from using Scrimba

### ISSUE THREAD

**Issue by hlabas** [scrimba/community#6]
Hi,

While creating a cast, I ran a script which contained errors which led the app not be unable to react afterwards. I had to delete the cast and start over.
The cast reference is 132.

Let me know if you need anything else.

Thanks!

**Comment by somebee** [comment]
We'll look into it! Working on a more robust pipeline for preprocessing and running scripts as part of our efforts to add support for babel, jsx and external scripts. I'll keep you posted :)

**Comment by somebee** [comment]
The way scripts are executed has been changed drastically over the last 3 months, so this problem is most likely fixed. Closing.
