### ISSUE TITLE
Increase font of page

### ISSUE THREAD

**Issue by zayn02** [scrimba/community#602]
dear scrimba, please check your front-end-development course that's all font size is increase automatically 
![Screenshot 2021-06-01 092810](https://user-images.githubusercontent.com/64209460/120359322-64759600-c2bc-11eb-8452-626bde55d206.png)

**Comment by raaghuu** [comment]
Same issue here

**Comment by Pistus** [comment]
Sometime´s you just forget to check all consequences of your actions - didnt realise that the Scrim page has a different base font size + its structure is based on div's instead of headers, p's, etc. If I understand the issue correct it is fixed.
