### ISSUE TITLE
Code execution fails

### ISSUE THREAD

**Issue by raaghuu** [scrimba/community#603]
Code not running on save in mini-browser

In React
![image](https://user-images.githubusercontent.com/7644986/120371603-ad1c6600-c333-11eb-96d0-9993401991a5.png)

In normal HTML
![image](https://user-images.githubusercontent.com/7644986/120371827-fbca0000-c333-11eb-9423-3eead9ded77e.png)

**Comment by teitrand** [comment]
I got the same error now.

**Comment by mahmoudsoudi** [comment]
I got the same error now.
