### ISSUE TITLE
Unenroll and reset feature on courses.

### ISSUE THREAD

**Issue by geraldelorm** [scrimba/community#612]
Kindly give users the ability to reset course progress or unenroll from courses entirely. 

Thanks, I love the scrimba platform.

**Comment by ShaniaKC** [comment]
First, Scrimba is amazing.

Please assign someone to this issue, It will be very helpful

**Comment by geraldelorm** [comment]
Ikr 😂, it's been almost a year

**Comment by nscdlg** [comment]
Please look at this closer @geraldelorm @ShaniaKC  
[![](https://res.cloudinary.com/do2jhv5ao/image/upload/v1669880020/Frame_1_2_zucunp.png)](https://res.cloudinary.com/do2jhv5ao/image/upload/v1669880020/Frame_1_2_zucunp.png)

**Comment by geraldelorm** [comment]
Looks good, thanks!

**Comment by C2GR** [comment]
Really? 4 years now and still nothing?

**Comment by nisacodelifings** [comment]
@C2GR I already answered and found the feature for this issue using my other account, @annisapussa. However, I noticed that the screenshot I attached is now gone there.
