### ISSUE TITLE
Issue on scrimba with invisible line on screen blocking cursor's click.

### ISSUE THREAD

**Issue by alvziz** [scrimba/community#627]
I have this issue on scrimba on the left side of my screen. I've had this on both of my Chromebooks, so I know it's not client side. There's an invisible block of line blocking my cursor's click and doesn't let me edit text. How can I solve this issue? I've disabled my extensions but it still doesn't work. 

It starts right under the index.html in the explorer tab and makes its way to the right across the screen. 

https://user-images.githubusercontent.com/91266041/142776646-1974832c-5f81-4b74-94d6-434f8b2966a9.mp4

**Comment by lkrryba** [comment]
Leanne talking to use on Discord regarding this. For now, issue can be closed.

**Comment by alvziz** [comment]
closing issue
