### ISSUE TITLE
Minibrowser not working in several modules / challenges

### ISSUE THREAD

**Issue by schn31d3r** [scrimba/community#632]
Hello,

i encountered a problem in the lessons mentioned above.
In the challenges for **building the carrousel** the **minibrowser does not work**.
It shows a **red background** and an **error message**. For more details **see the attached picture**.
Thanks!

![image](https://user-images.githubusercontent.com/26523731/149826611-1eb18818-a01d-452f-9e67-25edea8460f6.png)

Cheers,
Daniel

**Comment by AlishaSo** [comment]
I'm having the same problem in module 8 lesson 4 Grid & Fetch. Seems it's not module/lesson specific..

**Comment by schn31d3r** [comment]
Hello Alisha,

thanks for your reply. I took the liberty to update the heading of the issue. If anybody runs into the same problem it will be more easier for them to find it here :-).

For me the problem occured in: Modul 4 - JS challenges - lesson 14 to 24 (by this, none information of the original post is lost).

Cheers
Daniel

**Comment by schn31d3r** [comment]
Hello there,

solved the problem for me by disabling my Kaspersky Chrome plugin.

Cheers

**Comment by memanums** [comment]
@schn31d3r I was facing the same issue, kaspersky plugin was the culprit.
