### ISSUE TITLE
Cohort link seems broken (?)

### ISSUE THREAD

**Issue by FrenzyExists** [scrimba/community#635]
Sup! So while taking the course of Javascript (the free one) I stumbled upon the cohort video in between the lessons. However, when clicking this video as said, I get this:

![image](https://user-images.githubusercontent.com/47986470/157984812-e8cc7023-8471-40ed-8ae1-ba2b44511b6b.png)

When clicking that I end up in the vercel documentation. Bellow are my specs in case it helps for debugging:

![image](https://user-images.githubusercontent.com/47986470/157985068-d0602aee-5446-40f4-91c7-de62e4c332dc.png)

![image](https://user-images.githubusercontent.com/47986470/157985086-98ed22c8-2cde-402a-88ad-cbd43708fcee.png)

**Comment by Pistus** [comment]
Hi, sorry about that but the jscohort page was temporary and is now removed.
