### ISSUE TITLE
Bug in JavaScript execution or console

### ISSUE THREAD

**Issue by NonPolynomial** [scrimba/community#64]
In following cast I found a bug: [cN3LDHZ](https://scrimba.com/casts/cN3LDHZ).

I would expect, that the Array#filter function always returns an array and in the case that no item in array match the filter, an empty array (`[]`) will be returned.

But as you can see, in <kbd>console</kbd> `false` is returned.

**Comment by perborgen** [comment]
This is fixed in the latest deployment.
