### ISSUE TITLE
Mini browser is not working

### ISSUE THREAD

**Issue by wahedsikder** [scrimba/community#651]
![Screenshot_794](https://user-images.githubusercontent.com/40826486/214499612-610cd39a-8683-44bf-b8f8-bb8e7f8fad96.png)

Hi, 

The mini browser is rendering "**Missing cw2**" when running the code.

**Comment by Pistus** [comment]
Thanks for reporting this @wahedsikder - The cause was an expired SSL certificate (https) caused by a token that had expired It was fixed after around 1 hour.
