### ISSUE TITLE
My pointer not appear in Linux

### ISSUE THREAD

**Issue by ardianta** [scrimba/community#66]
Hello, I'm using Opera browser on Linux. My pointer did not appear in screencast.

**Comment by somebee** [comment]
Recording of pointer is currently disabled, due to be added in the next update. I'll notify you when it is enabled again :)

**Comment by ardianta** [comment]
Thank you for your answer @somebee, I'm waiting for it.

**Comment by somebee** [comment]
Recording pointer is now implemented again. We don't track pointer-interaction with the console atm, but it is in the pipeline.
