### ISSUE TITLE
GitHub Student Developer Pack

### ISSUE THREAD

**Issue by ChipRealz** [scrimba/community#661]
It is said in the GitHub Student Developer Pack that I enjoy 1 month of free access to Full access to Scrimba’s Pro courses, projects, and coding challenges, which includes 40+ courses. But when I log in using GitHub I can't access Scrimba’s Pro courses, projects, and coding challenges,

**Comment by Pistus** [comment]
Hi @ChipRealz, sorry for the late reply. If you are eligable in that your github user has a github student flag set you can go to [scrimba.com/github-education](https://scrimba.com/github-education) and click on the button to get more info. You should also have a coupon added to your user so you can go to the [checkout for pro](https://scrimba.com/pricing#join) and it should offer you to claim a month for free.
