### ISSUE TITLE
In the firefox, some tabs does not works fine.

### ISSUE THREAD

**Issue by NabiKAZ** [scrimba/community#68]
In the firefox, some tabs does not works fine.
FF 54.0.1 (64-bit)

![image](https://user-images.githubusercontent.com/246721/29563992-317ede4c-8755-11e7-8b1b-149905475bf0.png)

![image](https://user-images.githubusercontent.com/246721/29564000-38214050-8755-11e7-9fa6-17183f6aa203.png)

**Comment by perborgen** [comment]
How does the other pages look like @NabiKAZ ? The front page for example.

**Comment by NabiKAZ** [comment]
There is no problem in main page and showing learning page.

![image](https://user-images.githubusercontent.com/246721/29564645-f81ab3b2-8757-11e7-9a20-c1353cb633e3.png)

**Comment by Pistus** [comment]
Closing this as both FF and our site has changed a lot.
