### ISSUE TITLE
Bug: cut from beginning does not work

### ISSUE THREAD

**Issue by tsnieman** [scrimba/community#71]
https://github.com/scrimba/community/blob/master/DOCS.md#cut-beginning

Tried this :arrow_up:... the yellow triangles appear but cannot be dragged.

I'm using Chrome 60 (on Ubuntu).

**Comment by somebee** [comment]
The documentation is a little outdated, in combination with an issue with cutting / discarding recordings. Working on it today :)

**Comment by perborgen** [comment]
It works now, so closing this one.
