### ISSUE TITLE
Stop button doesn't work

### ISSUE THREAD

**Issue by davidgilbertson** [scrimba/community#72]
I started a new project. Then I got this error in the console when I pressed the stop button:

![image](https://user-images.githubusercontent.com/4443482/29947065-2d986e36-8eeb-11e7-850d-f62213730ea0.png)

I don't have a mic (I'm on a PC) and I noticed also that the drop down next to the audio icon is empty, when creating a project. Based on the console output maybe they're related? Is it trying to call `.stop()` on an audio element that doesn't exist? I have tried with and without audio checked.

![image](https://user-images.githubusercontent.com/4443482/29947044-19829c8c-8eeb-11e7-89f6-12b90e492004.png)

BTW Scrimba looks pretty cool, looking forward to using it.

Edit: if I plug a mic in, it all works.

**Comment by Pistus** [comment]
Closing as stale issue.
