### ISSUE TITLE
Initial NPM support

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#73]

**Comment by judofyr** [comment]
Pending tasks for first release:

- [ ] Run resolver-server in production
- [ ] Show progress when loading dependencies (it can take a while)
- [ ] Report when there's an error during loading
- [ ] Documentation
- [ ] Add example templates for React, Vue, etc.

Nice-to-have:

- [ ] Correct stack traces

**Comment by judofyr** [comment]
Deployed!
