### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by kingade** [scrimba/community#87]
There are no screencasts for the Python language.

**Comment by somebee** [comment]
This is on our roadmap. @judofyr is working on it - he can fill you in on the progress :)

**Comment by kingade** [comment]
ok awesome, looking forward to it then.

**Comment by judofyr** [comment]
The main work has currently been in #82 which is about storing terminal output/input in the stream. The next step is to actually execute Python code.

**Comment by PCabralSoftware** [comment]
Hello there @kingade! I made a simple workaround so you can use Python (except for prompt) in Scrimba. https://scrimba.com/p/pRB9Hw/cd9kPfE

The actual Python interpretation instead of transpiling will be available in a near future, stay tuned.

**Comment by meleantonio** [comment]
Hi @judofyr any update on this?

**Comment by blueeyes08** [comment]
I have made some python 101 casts using the Brython add-in...
Still some issues , like file access, that doesn't seem to work..
the help() function also seems broken
My playlist is here: [khan.co/pyth101](url)

**Comment by PCabralSoftware** [comment]
Hi @blueeyes08! For JS, Brython or anything on Scrimba, the filesystem is disabled permanently due to security reasons. The `help()` function is broken maybe because of the `fs`.

**Comment by scanf** [comment]
There is now a course available here https://scrimba.com/g/gpython
