### ISSUE TITLE
Audio recording randomly stops working

### ISSUE THREAD

**Issue by somebee** [scrimba/community#89]
Some users are experiencing issues where their audio-recording does not work. Currently you will only know this *after* finishing recording, which is a very frustrating user experience. We are working on detecting and notifying the users of this bug immediately before recording.

When you experience this, the only way to get your microphone to work again is by restarting chrome.

The actual bug in chrome can be tracked here:
[#654910 - MediaRecorder Gets into Bad State and Raises Empty Data Events](https://bugs.chromium.org/p/chromium/issues/detail?id=654910)

**Comment by Pistus** [comment]
Closing as stale issue.
