### ISSUE TITLE
Ability to change playback speed (0.5x, 1.5x, 2x)

### ISSUE THREAD

**Issue by judofyr** [scrimba/community#9]
Requested at https://news.ycombinator.com/item?id=13815243

**Comment by amark** [comment]
Yeah guys are amazing and I am very excited to use Scrimba. I usually tell people to play my screencasts (now scrimba!) recordings at 2X, so having this in scrimba would be nice (I don't know how hard this is though).

Are there ways to help out / contribute?

**Comment by somebee** [comment]
It's very easy. We had support for it in an earlier internal version, but temporarily removed it because it is not supported on mobile (Audio.playbackRate has poor mobile support). Will try to reenable it for desktop asap though :)

**Comment by amark** [comment]
@somebee @perborgen again, great work, just saw the follow up HN article - https://medium.freecodecamp.com/how-we-convinced-founder-angels-to-invest-in-our-developer-tool-startup-f2e3bc59cbcc#.o97uu9pqn .

Want to encourage you guys again, great post, good words, etc. and say (when you have time) let's connect more formally - I raised a half million for my Open Source developer tool project as well, from some great names like Tim Draper and Marc Benioff of Salesforce and others. Would love to chat, and see if I can help out anywhere. Cheers! (shoot me an email if you are interested: mark@gunDB.io )

**Comment by perborgen** [comment]
Yeah, let's schedule a chat, we'll email you :)

**Comment by perborgen** [comment]
This one has been deployed, so closing it.

**Comment by somebee** [comment]
Beware - playbackRate does not currently work when looking at your own casts (due to editing, the audio is played through web audio for your own casts). There are also issues on safari that we are looking into.

**Comment by somebee** [comment]
It should now work on Safari as well.

**Comment by amark** [comment]
Already available! Wow! You guys are beasts, you guys are machines! Awesome feature addition.
