### ISSUE TITLE
Img disappears on reload

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#97]
Try to reload the simulator on this playground.

https://scrimba.com/c/c73ZkU8

One of the images (of waves) disappears. Here's the error from the console:

<img width="1391" alt="skjermbilde 2017-10-04 kl 11 52 21" src="https://user-images.githubusercontent.com/2429547/31194069-dd014748-a8fa-11e7-8131-668daf9a1fba.png">

**Comment by somebee** [comment]
Does this still happen for you? It works for me here. I think the bug was related to #99, which has now been fixed.

**Comment by perborgen** [comment]
Now it works
